(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_chain_core]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Chain_Types.

(** Trait declaration: [umbra_chain_core::ChainHmac]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 143:0-145:1
    Visibility: public *)
Record ChainHmac_t (Self : Type) := mkChainHmac_t {
  ChainHmac_t_hmac_chain : Self -> array u8 32%usize -> array u8 292%usize ->
    result (array u8 32%usize);
}.

Arguments mkChainHmac_t { _ }.
Arguments ChainHmac_t_hmac_chain { _ } _.

End Chain_Types.
