(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_chain_core]: function definitions *)
Require Import Primitives.
Import Primitives.
Require Import AeneasLoopShim.
Import AeneasLoopShim.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Chain_Types.
Include Chain_Types.
Require Import Chain_FunsExternal.
Include Chain_FunsExternal.
Module Chain_Funs.

(** [umbra_chain_core::UMBR_MAGIC]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 76:0-76:40
    Visibility: public *)
Definition uMBR_MAGIC : u32 := 1380794965%u32.

(** [umbra_chain_core::HDR_LEN]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 78:0-78:30
    Visibility: public *)
Definition hDR_LEN : usize := 48%usize.

(** [umbra_chain_core::HDR_HMAC_OFF]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 81:0-81:35
    Visibility: public *)
Definition hDR_HMAC_OFF : usize := 16%usize.

(** [umbra_chain_core::CODE_SIZE_OFF]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 83:0-83:36
    Visibility: public *)
Definition cODE_SIZE_OFF : usize := 10%usize.

(** [umbra_chain_core::CODE_LEN]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 85:0-85:32
    Visibility: public *)
Definition cODE_LEN : usize := 256%usize.

(** [umbra_chain_core::META_LEN]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 87:0-87:31
    Visibility: public *)
Definition mETA_LEN : usize := 32%usize.

(** [umbra_chain_core::BLOCK_LEN]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 89:0-89:33
    Visibility: public *)
Definition bLOCK_LEN : usize := 288%usize.

(** [umbra_chain_core::BLOCK_PREIMAGE_LEN]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 91:0-91:42
    Visibility: public *)
Definition bLOCK_PREIMAGE_LEN : usize := 292%usize.

(** [umbra_chain_core::MAX_BLOCKS]
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 94:0-94:31
    Visibility: public *)
Definition mAX_BLOCKS : u32 := 64%u32.

(** [umbra_chain_core::block_preimage_of_block]:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 118:0-127:1
    Visibility: public *)
Definition block_preimage_of_block
  (blk : u32) (block : array u8 288%usize) : result (array u8 292%usize) :=
  let b := array_to_slice block in
  let pre := array_repeat 292%usize 0%u8 in
  p <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre
      {|
        core_ops_range_Range_start := 0%usize;
        core_ops_range_Range_end_ := 4%usize
      |};
  let (s, index_mut_back) := p in
  let a := core_num_U32_to_le_bytes blk in
  let s1 := array_to_slice a in
  s2 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s s1;
  let pre1 := index_mut_back s2 in
  p1 <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre1
      {|
        core_ops_range_Range_start := 4%usize;
        core_ops_range_Range_end_ := 260%usize
      |};
  let (s3, index_mut_back1) := p1 in
  s4 <-
    core_slice_index_Slice_index
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8) b
      {|
        core_ops_range_Range_start := mETA_LEN;
        core_ops_range_Range_end_ := bLOCK_LEN
      |};
  s5 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s3 s4;
  let pre2 := index_mut_back1 s5 in
  p2 <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre2
      {|
        core_ops_range_Range_start := 260%usize;
        core_ops_range_Range_end_ := 292%usize
      |};
  let (s6, index_mut_back2) := p2 in
  s7 <-
    core_slice_index_Slice_index
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8) b
      {|
        core_ops_range_Range_start := 0%usize;
        core_ops_range_Range_end_ := mETA_LEN
      |};
  s8 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s6 s7;
  Ok (index_mut_back2 s8)
.

(** [umbra_chain_core::block_preimage]:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 137:0-150:1
    Visibility: public *)
Definition block_preimage
  (blob : slice u8) (blk : u32) : result (option (array u8 292%usize)) :=
  if blk s>= mAX_BLOCKS
  then Ok None
  else (
    i <- scalar_cast U32 Usize blk;
    i1 <- usize_mul i bLOCK_LEN;
    base <- usize_add hDR_LEN i1;
    let i2 := slice_len blob in
    i3 <- usize_add base bLOCK_LEN;
    if i2 s< i3
    then Ok None
    else (
      let block := array_repeat 288%usize 0%u8 in
      p <-
        core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
          (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) block
          {|
            core_ops_range_Range_start := 0%usize;
            core_ops_range_Range_end_ := bLOCK_LEN
          |};
      let (s, index_mut_back) := p in
      s1 <-
        core_slice_index_Slice_index
          (core_slice_index_SliceIndexRangeUsizeSliceInst u8) blob
          {|
            core_ops_range_Range_start := base; core_ops_range_Range_end_ := i3
          |};
      s2 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s s1;
      let block1 := index_mut_back s2 in
      a <- block_preimage_of_block blk block1;
      Ok (Some a)))
.

(** [umbra_chain_core::chain_root]: loop body 0:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 162:4-172:1
    Visibility: public *)
Definition chain_root_loop_body
  {H : Type} (chainHmacInst : ChainHmac_t H) (h : H) (blob : slice u8)
  (num_blocks : u32) (chain : array u8 32%usize) (i : u32) :
  result (control_flow ((array u8 32%usize) * u32) (option (array u8
    32%usize)))
  :=
  if i s< num_blocks
  then (
    o <- block_preimage blob i;
    match o with
    | None => Ok (Done None)
    | Some pre =>
      chain1 <- chainHmacInst.(ChainHmac_t_hmac_chain) h chain pre;
      i1 <- u32_add i 1%u32;
      Ok (Cont (chain1, i1))
    end)
  else Ok (Done (Some chain))
.

(** [umbra_chain_core::chain_root]: loop 0:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 162:4-172:1
    Visibility: public *)
Definition chain_root_loop
  {H : Type} (chainHmacInst : ChainHmac_t H) (h : H) (blob : slice u8)
  (num_blocks : u32) (chain : array u8 32%usize) (i : u32) :
  result (option (array u8 32%usize))
  :=
  loop
    (fun '(chain1, i1) => chain_root_loop_body
      chainHmacInst h blob num_blocks chain1 i1)
    (chain, i)
.

(** [umbra_chain_core::chain_root]:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 154:0-172:1
    Visibility: public *)
Definition chain_root
  {H : Type} (chainHmacInst : ChainHmac_t H) (h : H)
  (master : array u8 32%usize) (blob : slice u8) (num_blocks : u32) :
  result (option (array u8 32%usize))
  :=
  chain_root_loop chainHmacInst h blob num_blocks master 0%u32
.

(** [umbra_chain_core::blob_block_count]:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 176:0-195:1
    Visibility: public *)
Definition blob_block_count (blob : slice u8) : result (option u32) :=
  let i := slice_len blob in
  if i s< hDR_LEN
  then Ok None
  else (
    i1 <- slice_index_usize blob 0%usize;
    i2 <- slice_index_usize blob 1%usize;
    i3 <- slice_index_usize blob 2%usize;
    i4 <- slice_index_usize blob 3%usize;
    let magic :=
      core_num_U32_from_le_bytes (mk_array4 i1 i2 i3 i4)
    in
    if magic s<> uMBR_MAGIC
    then Ok None
    else (
      i5 <- slice_index_usize blob cODE_SIZE_OFF;
      i6 <- usize_add cODE_SIZE_OFF 1%usize;
      i7 <- slice_index_usize blob i6;
      i9 <- usize_add cODE_SIZE_OFF 2%usize;
      i10 <- slice_index_usize blob i9;
      i11 <- usize_add cODE_SIZE_OFF 3%usize;
      i12 <- slice_index_usize blob i11;
      let code_size :=
        core_num_U32_from_le_bytes (mk_array4 i5 i7 i10 i12)
      in
      i13 <- scalar_cast Usize U32 bLOCK_LEN;
      n <- u32_div code_size i13;
      if n s= 0%u32
      then Ok None
      else if n s> mAX_BLOCKS then Ok None else Ok (Some n)))
.

(** [umbra_chain_core::ct_eq32_at]: loop body 0:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 220:4-223:5 *)
Definition ct_eq32_at_loop_body
  (a : array u8 32%usize) (blob : slice u8) (off : usize) (d : u8) (i : usize)
  :
  result (control_flow (u8 * usize) u8)
  :=
  if i s< 32%usize
  then (
    i1 <- array_index_usize a i;
    i2 <- usize_add off i;
    i3 <- slice_index_usize blob i2;
    let i4 := u8_xor i1 i3 in
    let d1 := u8_or d i4 in
    i5 <- usize_add i 1%usize;
    Ok (Cont (d1, i5)))
  else Ok (Done d)
.

(** [umbra_chain_core::ct_eq32_at]: loop 0:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 220:4-223:5 *)
Definition ct_eq32_at_loop
  (a : array u8 32%usize) (blob : slice u8) (off : usize) (d : u8) (i : usize)
  :
  result u8
  :=
  loop
    (fun '(d1, i1) => ct_eq32_at_loop_body a blob off d1 i1)
    (d, i)
.

(** [umbra_chain_core::ct_eq32_at]:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 214:0-225:1 *)
Definition ct_eq32_at
  (a : array u8 32%usize) (blob : slice u8) (off : usize) : result bool :=
  let i := slice_len blob in
  i1 <- usize_add off 32%usize;
  if i s< i1
  then Ok false
  else (d <- ct_eq32_at_loop a blob off 0%u8 0%usize; Ok (d s= 0%u8))
.

(** [umbra_chain_core::verify_blob_chain]:
    Source: 'crates/umbra-chain-core/src/lib.rs', lines 201:0-211:1
    Visibility: public *)
Definition verify_blob_chain
  {H : Type} (chainHmacInst : ChainHmac_t H) (h : H)
  (master : array u8 32%usize) (blob : slice u8) :
  result bool
  :=
  o <- blob_block_count blob;
  match o with
  | None => Ok false
  | Some n =>
    o1 <- chain_root chainHmacInst h master blob n;
    match o1 with
    | None => Ok false
    | Some r => ct_eq32_at r blob hDR_HMAC_OFF
    end
  end
.

End Chain_Funs.
