// Reads UMBRA_SLOT_SIZE_BYTES and UMBRA_CACHE_LIMIT from the environment
// (defaults supplied by.cargo/config.toml [env])
// and emits a generated Rust file with the resulting constants.
// ess.rs includes the file via the `include!` macro pattern,
// so the constants are visible across the kernel crate.
// The signing tool (tools/protect_enclave.py) reads the SAME env var,
// keeping kernel + tool layout in lockstep.
// rerun-if-env-changed makes Cargo re-emit the file when the variables
// change — without this the sweep harness would have to `cargo clean`
// between cells.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let slot_size: u32 = env::var("UMBRA_SLOT_SIZE_BYTES")
        .unwrap_or_else(|_| "256".into())
        .parse()
        .expect("UMBRA_SLOT_SIZE_BYTES must be a positive integer");

    let cache_limit: usize = env::var("UMBRA_CACHE_LIMIT")
        .unwrap_or_else(|_| "64".into())
        .parse()
        .expect("UMBRA_CACHE_LIMIT must be a non-negative integer");

    let max_enclaves_ctx: usize = env::var("UMBRA_MAX_ENCLAVES_CTX")
        .unwrap_or_else(|_| "2".into())
        .parse()
        .expect("UMBRA_MAX_ENCLAVES_CTX must be a positive integer");

    let psp_stack_bytes: u32 = env::var("UMBRA_ENCLAVE_PSP_STACK_BYTES")
        .unwrap_or_else(|_| "8192".into())
        .parse()
        .expect("UMBRA_ENCLAVE_PSP_STACK_BYTES must be a positive integer");

    let max_keys: usize = env::var("UMBRA_MAX_KEYS")
        .unwrap_or_else(|_| "8".into())
        .parse()
        .expect("UMBRA_MAX_KEYS must be a positive integer");

    println!("cargo:rerun-if-env-changed=UMBRA_SLOT_SIZE_BYTES");
    println!("cargo:rerun-if-env-changed=UMBRA_CACHE_LIMIT");
    println!("cargo:rerun-if-env-changed=UMBRA_MAX_ENCLAVES_CTX");
    println!("cargo:rerun-if-env-changed=UMBRA_ENCLAVE_PSP_STACK_BYTES");
    println!("cargo:rerun-if-env-changed=UMBRA_MAX_KEYS");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let generated = out_dir.join("sizes_generated.rs");

    let body = format!(
        "// Auto-generated by build.rs from the Stage A §Evaluation knobs.\n\
// DO NOT EDIT — re-run `cargo build` to regenerate. Source of truth:\n\
//.cargo/config.toml [env] (defaults) + shell env (overrides).\n\
pub const SLOT_SIZE: u32 = {slot_size};\n\
pub const SLOT_SIZE_USIZE: usize = {slot_size};\n\
pub const CACHE_LIMIT_PER_ENCLAVE: usize = {cache_limit};\n\
pub const MAX_ENCLAVES_CTX: usize = {max_enclaves_ctx};\n\
pub const ENCLAVE_PSP_STACK_SIZE: u32 = {psp_stack_bytes};\n\
pub const MAX_KEYS: usize = {max_keys};\n"
    );

    fs::write(&generated, body).expect("failed to write sizes_generated.rs");
}
