(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_mem_core]: function definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Mem_Types.
Include Mem_Types.
Module Mem_Funs.

(** [umbra_mem_core::MEMORY_BLOCK_SIZE]
    Source: '/Users/salvatorebramante/Downloads/umbra/target/aarch64-apple-darwin/debug/build/umbra-mem-core-92b1552863a3a71e/out/block_size_generated.rs', lines 1:0-1:39
    Visibility: public *)
Definition mEMORY_BLOCK_SIZE : u32 := 256%u32.

(** [umbra_mem_core::MEMORY_SUPER_BLOCK_SIZE]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 19:0-19:64
    Visibility: public *)
Definition mEMORY_SUPER_BLOCK_SIZE : result u32 :=
  u32_mul mEMORY_BLOCK_SIZE 16%u32
.

(** [umbra_mem_core::{impl core::clone::Clone for umbra_mem_core::MemoryBlockAccessAttribute}::clone]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 21:15-21:20
    Visibility: public *)
Definition MemoryBlockAccessAttribute_Insts_CoreCloneClone_clone
  (self : MemoryBlockAccessAttribute_t) :
  result MemoryBlockAccessAttribute_t
  :=
  Ok self
.

(** Trait implementation: [umbra_mem_core::{impl core::clone::Clone for umbra_mem_core::MemoryBlockAccessAttribute}]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 21:15-21:20 *)
Definition MemoryBlockAccessAttribute_Insts_CoreCloneClone : core_clone_Clone
  MemoryBlockAccessAttribute_t := {|
  core_clone_Clone_clone :=
    MemoryBlockAccessAttribute_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_mem_core::{impl core::marker::Copy for umbra_mem_core::MemoryBlockAccessAttribute}]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 21:9-21:13 *)
Definition MemoryBlockAccessAttribute_Insts_CoreMarkerCopy : core_marker_Copy
  MemoryBlockAccessAttribute_t := {|
  cloneInst := MemoryBlockAccessAttribute_Insts_CoreCloneClone;
|}.

(** [umbra_mem_core::{impl core::clone::Clone for umbra_mem_core::MemoryBlockSecurityAttribute}::clone]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 30:15-30:20
    Visibility: public *)
Definition MemoryBlockSecurityAttribute_Insts_CoreCloneClone_clone
  (self : MemoryBlockSecurityAttribute_t) :
  result MemoryBlockSecurityAttribute_t
  :=
  Ok self
.

(** Trait implementation: [umbra_mem_core::{impl core::clone::Clone for umbra_mem_core::MemoryBlockSecurityAttribute}]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 30:15-30:20 *)
Definition MemoryBlockSecurityAttribute_Insts_CoreCloneClone : core_clone_Clone
  MemoryBlockSecurityAttribute_t := {|
  core_clone_Clone_clone :=
    MemoryBlockSecurityAttribute_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_mem_core::{impl core::marker::Copy for umbra_mem_core::MemoryBlockSecurityAttribute}]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 30:9-30:13 *)
Definition MemoryBlockSecurityAttribute_Insts_CoreMarkerCopy : core_marker_Copy
  MemoryBlockSecurityAttribute_t := {|
  cloneInst := MemoryBlockSecurityAttribute_Insts_CoreCloneClone;
|}.

(** [umbra_mem_core::{impl core::clone::Clone for umbra_mem_core::MemoryBlock}::clone]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 37:15-37:20
    Visibility: public *)
Definition MemoryBlock_Insts_CoreCloneClone_clone
  (self : MemoryBlock_t) : result MemoryBlock_t :=
  Ok self
.

(** Trait implementation: [umbra_mem_core::{impl core::clone::Clone for umbra_mem_core::MemoryBlock}]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 37:15-37:20 *)
Definition MemoryBlock_Insts_CoreCloneClone : core_clone_Clone MemoryBlock_t
  := {|
  core_clone_Clone_clone := MemoryBlock_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_mem_core::{impl core::marker::Copy for umbra_mem_core::MemoryBlock}]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 37:9-37:13 *)
Definition MemoryBlock_Insts_CoreMarkerCopy : core_marker_Copy MemoryBlock_t
  := {|
  cloneInst := MemoryBlock_Insts_CoreCloneClone;
|}.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlock}::new]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 45:4-51:5
    Visibility: public *)
Definition memoryBlock_new : result MemoryBlock_t :=
  Ok
    {|
      memoryBlock_block_base_address := 0%u32;
      memoryBlock_block_access_attribute := MemoryBlockAccessAttribute_ReadOnly;
      memoryBlock_block_security_attribute :=
        MemoryBlockSecurityAttribute_Untrusted
    |}
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlock}::get_block_base_address]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 53:4-55:5
    Visibility: public *)
Definition memoryBlock_get_block_base_address
  (self : MemoryBlock_t) : result u32 :=
  Ok self.(memoryBlock_block_base_address)
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlock}::set_block_base_address]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 56:4-58:5
    Visibility: public *)
Definition memoryBlock_set_block_base_address
  (self : MemoryBlock_t) (address : u32) : result MemoryBlock_t :=
  Ok
    {|
      memoryBlock_block_base_address := address;
      memoryBlock_block_access_attribute :=
        self.(memoryBlock_block_access_attribute);
      memoryBlock_block_security_attribute :=
        self.(memoryBlock_block_security_attribute)
    |}
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlock}::get_block_access_attribute]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 59:4-61:5
    Visibility: public *)
Definition memoryBlock_get_block_access_attribute
  (self : MemoryBlock_t) : result MemoryBlockAccessAttribute_t :=
  Ok self.(memoryBlock_block_access_attribute)
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlock}::set_block_access_attribute]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 62:4-64:5
    Visibility: public *)
Definition memoryBlock_set_block_access_attribute
  (self : MemoryBlock_t) (attribute : MemoryBlockAccessAttribute_t) :
  result MemoryBlock_t
  :=
  Ok
    {|
      memoryBlock_block_base_address := self.(memoryBlock_block_base_address);
      memoryBlock_block_access_attribute := attribute;
      memoryBlock_block_security_attribute :=
        self.(memoryBlock_block_security_attribute)
    |}
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlock}::get_block_security_attribute]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 65:4-67:5
    Visibility: public *)
Definition memoryBlock_get_block_security_attribute
  (self : MemoryBlock_t) : result MemoryBlockSecurityAttribute_t :=
  Ok self.(memoryBlock_block_security_attribute)
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlock}::set_block_security_attribute]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 68:4-70:5
    Visibility: public *)
Definition memoryBlock_set_block_security_attribute
  (self : MemoryBlock_t) (attribute : MemoryBlockSecurityAttribute_t) :
  result MemoryBlock_t
  :=
  Ok
    {|
      memoryBlock_block_base_address := self.(memoryBlock_block_base_address);
      memoryBlock_block_access_attribute :=
        self.(memoryBlock_block_access_attribute);
      memoryBlock_block_security_attribute := attribute
    |}
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlockList}::create_from_range]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 83:4-98:5
    Visibility: public *)
Definition memoryBlockList_create_from_range
  (base_addr : u32) (limit_addr : u32) : result MemoryBlockList_t :=
  memory_block <- memoryBlock_new;
  i <- u32_div base_addr mEMORY_BLOCK_SIZE;
  memory_block1 <- memoryBlock_set_block_base_address memory_block i;
  i1 <- u32_sub limit_addr base_addr;
  memory_block_list_size <- u32_div i1 mEMORY_BLOCK_SIZE;
  let i2 := u32_and limit_addr 255%u32 in
  if i2 s<> 0%u32
  then (
    memory_block_list_size1 <- u32_add memory_block_list_size 1%u32;
    Ok
      {|
        memoryBlockList_memory_block := memory_block1;
        memoryBlockList_memory_block_list_size := memory_block_list_size1
      |})
  else
    Ok
      {|
        memoryBlockList_memory_block := memory_block1;
        memoryBlockList_memory_block_list_size := memory_block_list_size
      |}
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlockList}::get_memory_block]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 100:4-102:5
    Visibility: public *)
Definition memoryBlockList_get_memory_block
  (self : MemoryBlockList_t) : result MemoryBlock_t :=
  Ok self.(memoryBlockList_memory_block)
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlockList}::set_memory_block]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 103:4-105:5
    Visibility: public *)
Definition memoryBlockList_set_memory_block
  (self : MemoryBlockList_t) (block : MemoryBlock_t) :
  result MemoryBlockList_t
  :=
  Ok
    {|
      memoryBlockList_memory_block := block;
      memoryBlockList_memory_block_list_size :=
        self.(memoryBlockList_memory_block_list_size)
    |}
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlockList}::get_memory_block_list_size]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 106:4-108:5
    Visibility: public *)
Definition memoryBlockList_get_memory_block_list_size
  (self : MemoryBlockList_t) : result u32 :=
  Ok self.(memoryBlockList_memory_block_list_size)
.

(** [umbra_mem_core::{umbra_mem_core::MemoryBlockList}::set_memory_block_security]:
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 109:4-113:5
    Visibility: public *)
Definition memoryBlockList_set_memory_block_security
  (self : MemoryBlockList_t) (attribute : MemoryBlockSecurityAttribute_t) :
  result MemoryBlockList_t
  :=
  memory_block <- memoryBlockList_get_memory_block self;
  memory_block1 <-
    memoryBlock_set_block_security_attribute memory_block attribute;
  memoryBlockList_set_memory_block self memory_block1
.

End Mem_Funs.
