(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_mem_core]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Mem_Types.

(** [umbra_mem_core::MemoryBlockAccessAttribute]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 22:0-26:1
    Visibility: public *)
Inductive MemoryBlockAccessAttribute_t :=
| MemoryBlockAccessAttribute_ReadOnly : MemoryBlockAccessAttribute_t
| MemoryBlockAccessAttribute_ReadWrite : MemoryBlockAccessAttribute_t
| MemoryBlockAccessAttribute_ReadExecutable : MemoryBlockAccessAttribute_t
.

(** [umbra_mem_core::MemoryBlockSecurityAttribute]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 31:0-35:1
    Visibility: public *)
Inductive MemoryBlockSecurityAttribute_t :=
| MemoryBlockSecurityAttribute_Untrusted : MemoryBlockSecurityAttribute_t
| MemoryBlockSecurityAttribute_Trusted : MemoryBlockSecurityAttribute_t
| MemoryBlockSecurityAttribute_TrustedGateway : MemoryBlockSecurityAttribute_t
.

(** [umbra_mem_core::MemoryBlock]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 38:0-42:1
    Visibility: public *)
Record MemoryBlock_t :=
mkMemoryBlock_t {
  memoryBlock_block_base_address : u32;
  memoryBlock_block_access_attribute : MemoryBlockAccessAttribute_t;
  memoryBlock_block_security_attribute : MemoryBlockSecurityAttribute_t;
}
.

(** [umbra_mem_core::MemoryBlockList]
    Source: 'crates/umbra-mem-core/src/lib.rs', lines 74:0-77:1
    Visibility: public *)
Record MemoryBlockList_t :=
mkMemoryBlockList_t {
  memoryBlockList_memory_block : MemoryBlock_t;
  memoryBlockList_memory_block_list_size : u32;
}
.

End Mem_Types.
