(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_ess_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes. *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Ess_Types.
Include Ess_Types.
Module Ess_FunsExternal_Template.

(** [core::cmp::impls::{impl core::cmp::PartialEq<usize> for usize}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1878:16-1878:50
    Name pattern: [core::cmp::impls::{core::cmp::PartialEq<usize, usize>}::eq]
    Visibility: public *)
Axiom Usize_Insts_CoreCmpPartialEqUsize_eq : usize -> usize -> result bool.

(** [core::cmp::impls::{impl core::cmp::PartialOrd<usize> for usize}::partial_cmp]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1999:16-1999:71
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<usize, usize>}::partial_cmp]
    Visibility: public *)
Axiom Usize_Insts_CoreCmpPartialOrdUsize_partial_cmp
  : usize -> usize -> result (option core_cmp_Ordering_t)
.

(** [core::convert::{impl core::convert::From<T> for T}::from]:
    Source: '/rustc/library/core/src/convert/mod.rs', lines 788:4-788:22
    Name pattern: [core::convert::{core::convert::From<@T, @T>}::from]
    Visibility: public *)
Axiom core_convert_From_Blanket_from : forall{T : Type}, T -> result T.

(** [core::iter::range::{impl core::iter::range::Step for usize}::backward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 290:16-290:74
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::backward_checked]
    Visibility: public *)
Axiom Usize_Insts_CoreIterRangeStep_backward_checked
  : usize -> usize -> result (option usize)
.

(** [core::iter::range::{impl core::iter::range::Step for usize}::forward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 282:16-282:73
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::forward_checked]
    Visibility: public *)
Axiom Usize_Insts_CoreIterRangeStep_forward_checked
  : usize -> usize -> result (option usize)
.

(** [core::iter::range::{impl core::iter::range::Step for usize}::steps_between]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 271:16-271:84
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::steps_between]
    Visibility: public *)
Axiom Usize_Insts_CoreIterRangeStep_steps_between
  : usize -> usize -> result (usize * (option usize))
.

(** [core::iter::range::{impl core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::next]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 984:4-984:35
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::next]
    Visibility: public *)
Axiom core_ops_range_Range_Insts_CoreIterTraitsIteratorIterator_next :
  forall{A : Type} (stepInst : core_iter_range_Step_t A),
        core_ops_range_Range A -> result ((option A) * (core_ops_range_Range
          A))
.

(** [core::option::{core::option::Option<T>}::is_none]:
    Source: '/rustc/library/core/src/option.rs', lines 681:4-681:39
    Name pattern: [core::option::{core::option::Option<@T>}::is_none]
    Visibility: public *)
Axiom core_option_Option_is_none : forall{T : Type}, option T -> result bool.

(** [core::option::{core::option::Option<T>}::map]:
    Source: '/rustc/library/core/src/option.rs', lines 1157:4-1159:53
    Name pattern: [core::option::{core::option::Option<@T>}::map]
    Visibility: public *)
Axiom core_option_Option_map :
  forall{T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
        core_ops_function_FnOnce_t F T U),
        option T -> F -> result (option U)
.

(** [core::option::{core::option::Option<T>}::ok_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1334:4-1334:73
    Name pattern: [core::option::{core::option::Option<@T>}::ok_or]
    Visibility: public *)
Axiom core_option_Option_ok_or :
  forall{T : Type} {E : Type},
        option T -> E -> result (core_result_Result_t T E)
.

(** [core::option::{core::option::Option<T>}::and_then]:
    Source: '/rustc/library/core/src/option.rs', lines 1538:4-1540:61
    Name pattern: [core::option::{core::option::Option<@T>}::and_then]
    Visibility: public *)
Axiom core_option_Option_and_then :
  forall{T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTOptionInst :
        core_ops_function_FnOnce_t F T (option U)),
        option T -> F -> result (option U)
.

(** [core::result::{impl core::ops::try_trait::Try for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2177:4-2177:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch]
    Visibility: public *)
Axiom core_result_Result_Insts_CoreOpsTry_traitTry_branch :
  forall{T : Type} {E : Type},
        core_result_Result_t T E -> result (core_ops_control_flow_ControlFlow_t
          (core_result_Result_t core_convert_Infallible_t E) T)
.

(** [core::result::{impl core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2192:4-2192:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public *)
Axiom
  core_result_Result_Insts_CoreOpsTry_traitFromResidualResultInfallibleE_from_residual
  :
  forall(T : Type) {E : Type} {F : Type} (convertFromInst : core_convert_From F
        E),
        core_result_Result_t core_convert_Infallible_t E -> result
          (core_result_Result_t T F)
.

(** [core::slice::iter::{impl core::iter::traits::iterator::Iterator<&'a mut T> for core::slice::iter::IterMut<'a, T>}::next]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 157:12-157:47
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::IterMut<'a, @T>, &'a mut @T>}::next]
    Visibility: public *)
Axiom core_slice_iter_IterMut_Insts_CoreIterTraitsIteratorIteratorMutAT_next :
  forall{T : Type},
        core_slice_iter_IterMut_t T -> result ((option T) *
          (core_slice_iter_IterMut_t T) * (core_slice_iter_IterMut_t T ->
          option T -> core_slice_iter_IterMut_t T))
.

(** [core::slice::iter::{impl core::iter::traits::iterator::Iterator<&'a T> for core::slice::iter::Iter<'a, T>}::next]:
    Source: '/rustc/library/core/src/slice/iter/macros.rs', lines 157:12-157:47
    Name pattern: [core::slice::iter::{core::iter::traits::iterator::Iterator<core::slice::iter::Iter<'a, @T>, &'a @T>}::next]
    Visibility: public *)
Axiom core_slice_iter_Iter_Insts_CoreIterTraitsIteratorIteratorSharedAT_next :
  forall{T : Type},
        core_slice_iter_Iter_t T -> result ((option T) *
          (core_slice_iter_Iter_t T))
.

(** [core::slice::{[T]}::iter]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 1041:4-1041:43
    Name pattern: [core::slice::{[@T]}::iter]
    Visibility: public *)
Axiom core_slice_Slice_iter :
  forall{T : Type}, slice T -> result (core_slice_iter_Iter_t T)
.

(** [core::slice::{[T]}::iter_mut]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 1061:4-1061:54
    Name pattern: [core::slice::{[@T]}::iter_mut]
    Visibility: public *)
Axiom core_slice_Slice_iter_mut :
  forall{T : Type},
        slice T -> result ((core_slice_iter_IterMut_t T) *
          (core_slice_iter_IterMut_t T -> slice T))
.

End Ess_FunsExternal_Template.
