(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_ess_core]: function definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import AeneasLoopShim.
Import AeneasLoopShim.
Require Import Ess_Types.
Include Ess_Types.
Require Import Ess_FunsExternal.
Include Ess_FunsExternal.
Module Ess_Funs.

(** Trait implementation: [core::convert::{impl core::convert::From<T> for T}]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 785:0-785:27
    Name pattern: [core::convert::From<@T, @T>] *)
Definition core_convert_From_Blanket (T : Type) : core_convert_From T T := {|
  from_ := core_convert_From_Blanket_from;
|}.

(** Trait implementation: [core::iter::range::{impl core::iter::range::Step for usize}]
    Source: '/rustc/library/core/src/iter/range.rs', lines 266:12-266:43
    Name pattern: [core::iter::range::Step<usize>] *)
Definition Usize_Insts_CoreIterRangeStep : core_iter_range_Step_t usize := {|
  core_iter_range_Step_tcore_iter_range_Step_t_cloneCloneInst :=
    core_clone_CloneUsize;
  core_iter_range_Step_tcore_iter_range_Step_t_cmpPartialOrdInst :=
    core_cmp_PartialOrdUsize;
  core_iter_range_Step_t_steps_between :=
    Usize_Insts_CoreIterRangeStep_steps_between;
  core_iter_range_Step_t_forward_checked :=
    Usize_Insts_CoreIterRangeStep_forward_checked;
  core_iter_range_Step_t_backward_checked :=
    Usize_Insts_CoreIterRangeStep_backward_checked;
|}.

(** [umbra_ess_core::SLOT_SIZE]
    Source: '/Users/salvatorebramante/Downloads/umbra/crates/umbra-ess-core/target/aarch64-apple-darwin/debug/build/umbra-ess-core-39e48ce627427971/out/sizes_generated.rs', lines 1:0-1:31
    Visibility: public *)
Definition sLOT_SIZE : u32 := 256%u32.

(** [umbra_ess_core::SLOT_SIZE_USIZE]
    Source: '/Users/salvatorebramante/Downloads/umbra/crates/umbra-ess-core/target/aarch64-apple-darwin/debug/build/umbra-ess-core-39e48ce627427971/out/sizes_generated.rs', lines 2:0-2:39
    Visibility: public *)
Definition sLOT_SIZE_USIZE : usize := 256%usize.

(** [umbra_ess_core::CACHE_LIMIT_PER_ENCLAVE]
    Source: '/Users/salvatorebramante/Downloads/umbra/crates/umbra-ess-core/target/aarch64-apple-darwin/debug/build/umbra-ess-core-39e48ce627427971/out/sizes_generated.rs', lines 3:0-3:46
    Visibility: public *)
Definition cACHE_LIMIT_PER_ENCLAVE : usize := 64%usize.

(** [umbra_ess_core::MAX_ENCLAVES_CTX]
    Source: '/Users/salvatorebramante/Downloads/umbra/crates/umbra-ess-core/target/aarch64-apple-darwin/debug/build/umbra-ess-core-39e48ce627427971/out/sizes_generated.rs', lines 4:0-4:38
    Visibility: public *)
Definition mAX_ENCLAVES_CTX : usize := 2%usize.

(** [umbra_ess_core::ENCLAVE_PSP_STACK_SIZE]
    Source: '/Users/salvatorebramante/Downloads/umbra/crates/umbra-ess-core/target/aarch64-apple-darwin/debug/build/umbra-ess-core-39e48ce627427971/out/sizes_generated.rs', lines 5:0-5:45
    Visibility: public *)
Definition eNCLAVE_PSP_STACK_SIZE : u32 := 8192%u32.

(** [umbra_ess_core::MAX_KEYS]
    Source: '/Users/salvatorebramante/Downloads/umbra/crates/umbra-ess-core/target/aarch64-apple-darwin/debug/build/umbra-ess-core-39e48ce627427971/out/sizes_generated.rs', lines 6:0-6:30
    Visibility: public *)
Definition mAX_KEYS : usize := 8%usize.

(** [umbra_ess_core::ESS_BASE]
    Source: 'src/lib.rs', lines 72:0-72:38
    Visibility: public *)
Definition eSS_BASE : u32 := 65536%u32.

(** [umbra_ess_core::ESS_SIZE]
    Source: 'src/lib.rs', lines 78:0-78:34
    Visibility: public *)
Definition eSS_SIZE : u32 := 65536%u32.

(** [umbra_ess_core::EFBC_BASE]
    Source: 'src/lib.rs', lines 84:0-84:39
    Visibility: public *)
Definition eFBC_BASE : u32 := 131072%u32.

(** [umbra_ess_core::ENCLAVE_PSP_BASE]
    Source: 'src/lib.rs', lines 90:0-90:46
    Visibility: public *)
Definition eNCLAVE_PSP_BASE : u32 := 196608%u32.

(** [umbra_ess_core::ENCLAVE_PSP_TOP]
    Source: 'src/lib.rs', lines 96:0-96:45
    Visibility: public *)
Definition eNCLAVE_PSP_TOP : u32 := 212992%u32.

(** [umbra_ess_core::MAX_EFBS]
    Source: 'src/lib.rs', lines 105:0-105:31
    Visibility: public *)
Definition mAX_EFBS : usize := 64%usize.

(** [umbra_ess_core::MAX_REACHABLE]
    Source: 'src/lib.rs', lines 106:0-106:35
    Visibility: public *)
Definition mAX_REACHABLE : usize := 4%usize.

(** [umbra_ess_core::_]
    Source: 'src/lib.rs', lines 110:0-114:2 *)
Definition _ : result unit :=
  i <- scalar_cast U32 Usize eNCLAVE_PSP_STACK_SIZE;
  i1 <- usize_mul mAX_ENCLAVES_CTX i;
  i2 <- u32_sub eNCLAVE_PSP_TOP eNCLAVE_PSP_BASE;
  i3 <- scalar_cast U32 Usize i2;
  massert (i1 s<= i3)
.

(** [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::EnclaveDescriptor}::clone]:
    Source: 'src/lib.rs', lines 118:15-118:20
    Visibility: public *)
Definition EnclaveDescriptor_Insts_CoreCloneClone_clone
  (self : EnclaveDescriptor_t) : result EnclaveDescriptor_t :=
  Ok self
.

(** Trait implementation: [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::EnclaveDescriptor}]
    Source: 'src/lib.rs', lines 118:15-118:20 *)
Definition EnclaveDescriptor_Insts_CoreCloneClone : core_clone_Clone
  EnclaveDescriptor_t := {|
  core_clone_Clone_clone := EnclaveDescriptor_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_ess_core::{impl core::marker::Copy for umbra_ess_core::EnclaveDescriptor}]
    Source: 'src/lib.rs', lines 118:9-118:13 *)
Definition EnclaveDescriptor_Insts_CoreMarkerCopy : core_marker_Copy
  EnclaveDescriptor_t := {|
  cloneInst := EnclaveDescriptor_Insts_CoreCloneClone;
|}.

(** [umbra_ess_core::{umbra_ess_core::EnclaveDescriptor}::new]:
    Source: 'src/lib.rs', lines 129:4-138:5
    Visibility: public *)
Definition enclaveDescriptor_new : result EnclaveDescriptor_t :=
  Ok
    {|
      enclaveDescriptor_id := 0%u32;
      enclaveDescriptor_flash_base := 0%u32;
      enclaveDescriptor_ram_base := 0%u32;
      enclaveDescriptor_code_size := 0%u32;
      enclaveDescriptor_entry_point := 0%u32;
      enclaveDescriptor_is_loaded := false
    |}
.

(** [umbra_ess_core::enclave_psp_top]:
    Source: 'src/lib.rs', lines 141:0-143:1
    Visibility: public *)
Definition enclave_psp_top (enclave_idx : usize) : result u32 :=
  i <- scalar_cast Usize U32 enclave_idx;
  i1 <- u32_mul i eNCLAVE_PSP_STACK_SIZE;
  u32_sub eNCLAVE_PSP_TOP i1
.

(** [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::EnclaveSwapSpace}::clone]:
    Source: 'src/lib.rs', lines 145:9-145:14
    Visibility: public *)
Definition EnclaveSwapSpace_Insts_CoreCloneClone_clone
  (self : EnclaveSwapSpace_t) : result EnclaveSwapSpace_t :=
  Ok self
.

(** Trait implementation: [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::EnclaveSwapSpace}]
    Source: 'src/lib.rs', lines 145:9-145:14 *)
Definition EnclaveSwapSpace_Insts_CoreCloneClone : core_clone_Clone
  EnclaveSwapSpace_t := {|
  core_clone_Clone_clone := EnclaveSwapSpace_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_ess_core::{impl core::marker::Copy for umbra_ess_core::EnclaveSwapSpace}]
    Source: 'src/lib.rs', lines 145:16-145:20 *)
Definition EnclaveSwapSpace_Insts_CoreMarkerCopy : core_marker_Copy
  EnclaveSwapSpace_t := {|
  cloneInst := EnclaveSwapSpace_Insts_CoreCloneClone;
|}.

(** [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::EfbDescriptor}::clone]:
    Source: 'src/lib.rs', lines 153:9-153:14
    Visibility: public *)
Definition EfbDescriptor_Insts_CoreCloneClone_clone
  (self : EfbDescriptor_t) : result EfbDescriptor_t :=
  Ok self
.

(** Trait implementation: [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::EfbDescriptor}]
    Source: 'src/lib.rs', lines 153:9-153:14 *)
Definition EfbDescriptor_Insts_CoreCloneClone : core_clone_Clone
  EfbDescriptor_t := {|
  core_clone_Clone_clone := EfbDescriptor_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_ess_core::{impl core::marker::Copy for umbra_ess_core::EfbDescriptor}]
    Source: 'src/lib.rs', lines 153:16-153:20 *)
Definition EfbDescriptor_Insts_CoreMarkerCopy : core_marker_Copy
  EfbDescriptor_t := {|
  cloneInst := EfbDescriptor_Insts_CoreCloneClone;
|}.

(** [umbra_ess_core::{impl core::default::Default for umbra_ess_core::EfbDescriptor}::default]:
    Source: 'src/lib.rs', lines 163:4-171:5
    Visibility: public *)
Definition EfbDescriptor_Insts_CoreDefaultDefault_default
  : result EfbDescriptor_t :=
  let a := array_repeat 4%usize 0%u8 in
  Ok
    {|
      efbDescriptor_id := 0%u32;
      efbDescriptor_is_loaded := false;
      efbDescriptor_counter := 0%u8;
      efbDescriptor_reachable := a;
      efbDescriptor_reachable_count := 0%u8
    |}
.

(** Trait implementation: [umbra_ess_core::{impl core::default::Default for umbra_ess_core::EfbDescriptor}]
    Source: 'src/lib.rs', lines 162:0-172:1 *)
Definition EfbDescriptor_Insts_CoreDefaultDefault : core_default_Default_t
  EfbDescriptor_t := {|
  core_default_Default_t_default :=
    EfbDescriptor_Insts_CoreDefaultDefault_default;
|}.

(** [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::LoadedEnclave}::clone]:
    Source: 'src/lib.rs', lines 174:9-174:14
    Visibility: public *)
Definition LoadedEnclave_Insts_CoreCloneClone_clone
  (self : LoadedEnclave_t) : result LoadedEnclave_t :=
  Ok self
.

(** Trait implementation: [umbra_ess_core::{impl core::clone::Clone for umbra_ess_core::LoadedEnclave}]
    Source: 'src/lib.rs', lines 174:9-174:14 *)
Definition LoadedEnclave_Insts_CoreCloneClone : core_clone_Clone
  LoadedEnclave_t := {|
  core_clone_Clone_clone := LoadedEnclave_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_ess_core::{impl core::marker::Copy for umbra_ess_core::LoadedEnclave}]
    Source: 'src/lib.rs', lines 174:16-174:20 *)
Definition LoadedEnclave_Insts_CoreMarkerCopy : core_marker_Copy
  LoadedEnclave_t := {|
  cloneInst := LoadedEnclave_Insts_CoreCloneClone;
|}.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::new]:
    Source: 'src/lib.rs', lines 183:4-190:5
    Visibility: public *)
Definition enclaveSwapSpace_new : result EnclaveSwapSpace_t :=
  let a := array_repeat 2%usize None in
  let a1 := array_repeat 8%usize 0%u32 in
  Ok
    {|
      enclaveSwapSpace_base_address := eSS_BASE;
      enclaveSwapSpace_size := eSS_SIZE;
      enclaveSwapSpace_loaded_enclaves := a;
      enclaveSwapSpace_bitmap := a1
    |}
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::mark_slots_used]: loop body 0:
    Source: 'src/lib.rs', lines 249:8-253:9 *)
Definition enclaveSwapSpace_mark_slots_used_loop_body
  (start : usize) (count : usize) (self : EnclaveSwapSpace_t) (k : usize) :
  result (control_flow (EnclaveSwapSpace_t * usize) EnclaveSwapSpace_t)
  :=
  if k s< count
  then (
    idx <- usize_add start k;
    i <- usize_rem idx 32%usize;
    i1 <- u32_shl 1%u32 i;
    i2 <- usize_div idx 32%usize;
    i3 <- array_index_usize self.(enclaveSwapSpace_bitmap) i2;
    let i4 := u32_or i3 i1 in
    a <- array_update_usize self.(enclaveSwapSpace_bitmap) i2 i4;
    k1 <- usize_add k 1%usize;
    Ok (Cont
      ({|
         enclaveSwapSpace_base_address := self.(enclaveSwapSpace_base_address);
         enclaveSwapSpace_size := self.(enclaveSwapSpace_size);
         enclaveSwapSpace_loaded_enclaves :=
           self.(enclaveSwapSpace_loaded_enclaves);
         enclaveSwapSpace_bitmap := a
       |}, k1)))
  else Ok (Done self)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::mark_slots_used]: loop 0:
    Source: 'src/lib.rs', lines 249:8-253:9 *)
Definition enclaveSwapSpace_mark_slots_used_loop
  (self : EnclaveSwapSpace_t) (start : usize) (count : usize) (k : usize) :
  result EnclaveSwapSpace_t
  :=
  loop
    (fun ((self1, k1) : (EnclaveSwapSpace_t * usize)) =>
      enclaveSwapSpace_mark_slots_used_loop_body start count self1 k1)
    (self, k)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::mark_slots_used]:
    Source: 'src/lib.rs', lines 247:4-254:5 *)
Definition enclaveSwapSpace_mark_slots_used
  (self : EnclaveSwapSpace_t) (start : usize) (count : usize) :
  result EnclaveSwapSpace_t
  :=
  enclaveSwapSpace_mark_slots_used_loop self start count 0%usize
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::find_free_run]: loop body 0:
    Source: 'src/lib.rs', lines 228:8-244:5 *)
Definition enclaveSwapSpace_find_free_run_loop_body
  (self : EnclaveSwapSpace_t) (slots_needed : u32) (total_slots : usize)
  (found_count : u32) (i : usize) :
  result (control_flow (u32 * usize) (option usize))
  :=
  if i s< total_slots
  then (
    word_idx <- usize_div i 32%usize;
    bit_idx <- usize_rem i 32%usize;
    i1 <- array_index_usize self.(enclaveSwapSpace_bitmap) word_idx;
    i2 <- u32_shl 1%u32 bit_idx;
    let i3 := u32_and i1 i2 in
    found_count1 <-
      if i3 s= 0%u32 then u32_add found_count 1%u32 else Ok 0%u32;
    if found_count1 s= slots_needed
    then (
      i4 <- usize_add i 1%usize;
      i5 <- scalar_cast U32 Usize slots_needed;
      i6 <- usize_sub i4 i5;
      Ok (Done (Some i6)))
    else (i4 <- usize_add i 1%usize; Ok (Cont (found_count1, i4))))
  else Ok (Done None)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::find_free_run]: loop 0:
    Source: 'src/lib.rs', lines 228:8-244:5 *)
Definition enclaveSwapSpace_find_free_run_loop
  (self : EnclaveSwapSpace_t) (slots_needed : u32) (total_slots : usize)
  (found_count : u32) (i : usize) :
  result (option usize)
  :=
  loop
    (fun ((found_count1, i1) : (u32 * usize)) =>
      enclaveSwapSpace_find_free_run_loop_body self slots_needed total_slots
      found_count1 i1)
    (found_count, i)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::find_free_run]:
    Source: 'src/lib.rs', lines 219:4-244:5 *)
Definition enclaveSwapSpace_find_free_run
  (self : EnclaveSwapSpace_t) (slots_needed : u32) : result (option usize) :=
  i <- u32_div eSS_SIZE sLOT_SIZE;
  total_slots <- scalar_cast U32 Usize i;
  enclaveSwapSpace_find_free_run_loop self slots_needed total_slots 0%u32
    0%usize
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::allocate]:
    Source: 'src/lib.rs', lines 199:4-214:5
    Visibility: public *)
Definition enclaveSwapSpace_allocate
  (self : EnclaveSwapSpace_t) (size : u32) :
  result ((core_result_Result_t u32 umbra_error_UmbraError_t) *
    EnclaveSwapSpace_t)
  :=
  i <- u32_sub sLOT_SIZE 1%u32;
  let o := U32_checked_add size i in
  r <- core_option_Option_ok_or o Umbra_error_UmbraError_OffsetOverflow;
  cf <- core_result_Result_Insts_CoreOpsTry_traitTry_branch r;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue val =>
    slots_needed <- u32_div val sLOT_SIZE;
    if slots_needed s= 0%u32
    then
      Ok (Core_result_Result_Err Umbra_error_UmbraError_LengthMismatch, self)
    else (
      o1 <- enclaveSwapSpace_find_free_run self slots_needed;
      match o1 with
      | None =>
        Ok (Core_result_Result_Err Umbra_error_UmbraError_EssRegionExhausted,
          self)
      | Some found_start =>
        i1 <- scalar_cast U32 Usize slots_needed;
        self1 <- enclaveSwapSpace_mark_slots_used self found_start i1;
        i2 <- scalar_cast Usize U32 found_start;
        i3 <- u32_mul i2 sLOT_SIZE;
        i4 <- u32_add eFBC_BASE i3;
        Ok (Core_result_Result_Ok i4, self1)
      end)
  | Core_ops_control_flow_ControlFlow_Break residual =>
    r1 <-
      core_result_Result_Insts_CoreOpsTry_traitFromResidualResultInfallibleE_from_residual
        u32 (core_convert_From_Blanket umbra_error_UmbraError_t) residual;
    Ok (r1, self)
  end
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::release::BITMAP_CAPACITY]
    Source: 'src/lib.rs', lines 266:12-266:47 *)
Definition enclaveSwapSpace_release_BITMAP_CAPACITY : usize := 256%usize.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::release]: loop body 0:
    Source: 'src/lib.rs', lines 264:8-271:9
    Visibility: public *)
Definition enclaveSwapSpace_release_loop_body
  (slot_offset : u32) (slots : u32) (self : EnclaveSwapSpace_t) (k : u32) :
  result (control_flow (EnclaveSwapSpace_t * u32) EnclaveSwapSpace_t)
  :=
  if k s< slots
  then (
    i <- u32_add slot_offset k;
    idx <- scalar_cast U32 Usize i;
    self1 <-
      if idx s< enclaveSwapSpace_release_BITMAP_CAPACITY
      then (
        i1 <- usize_rem idx 32%usize;
        i2 <- u32_shl 1%u32 i1;
        let i3 := scalar_not i2 in
        i4 <- usize_div idx 32%usize;
        i5 <- array_index_usize self.(enclaveSwapSpace_bitmap) i4;
        let i6 := u32_and i5 i3 in
        a <- array_update_usize self.(enclaveSwapSpace_bitmap) i4 i6;
        Ok
          {|
            enclaveSwapSpace_base_address :=
              self.(enclaveSwapSpace_base_address);
            enclaveSwapSpace_size := self.(enclaveSwapSpace_size);
            enclaveSwapSpace_loaded_enclaves :=
              self.(enclaveSwapSpace_loaded_enclaves);
            enclaveSwapSpace_bitmap := a
          |})
      else Ok self;
    k1 <- u32_add k 1%u32;
    Ok (Cont (self1, k1)))
  else Ok (Done self)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::release]: loop 0:
    Source: 'src/lib.rs', lines 264:8-271:9
    Visibility: public *)
Definition enclaveSwapSpace_release_loop
  (self : EnclaveSwapSpace_t) (slot_offset : u32) (slots : u32) (k : u32) :
  result EnclaveSwapSpace_t
  :=
  loop
    (fun ((self1, k1) : (EnclaveSwapSpace_t * u32)) =>
      enclaveSwapSpace_release_loop_body slot_offset slots self1 k1)
    (self, k)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::release]:
    Source: 'src/lib.rs', lines 257:4-272:5
    Visibility: public *)
Definition enclaveSwapSpace_release
  (self : EnclaveSwapSpace_t) (address : u32) (size : u32) :
  result EnclaveSwapSpace_t
  :=
  if address s< eFBC_BASE
  then Ok self
  else (
    i <- u32_sub address eFBC_BASE;
    slot_offset <- u32_div i sLOT_SIZE;
    i1 <- u32_add size sLOT_SIZE;
    i2 <- u32_sub i1 1%u32;
    slots <- u32_div i2 sLOT_SIZE;
    enclaveSwapSpace_release_loop self slot_offset slots 0%u32)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::register_enclave]: loop body 0:
    Source: 'src/lib.rs', lines 281:8-293:5
    Visibility: public *)
Definition enclaveSwapSpace_register_enclave_loop_body
  (descriptor : EnclaveDescriptor_t) (address : u32)
  (efbs : array EfbDescriptor_t 64%usize) (efb_count : usize)
  (iter : core_slice_iter_IterMut_t (option LoadedEnclave_t))
  (back : core_slice_iter_IterMut_t (option LoadedEnclave_t) ->
  core_slice_iter_IterMut_t (option LoadedEnclave_t)) :
  result (control_flow ((core_slice_iter_IterMut_t (option LoadedEnclave_t)) *
    (core_slice_iter_IterMut_t (option LoadedEnclave_t) ->
    core_slice_iter_IterMut_t (option LoadedEnclave_t))) (bool *
    (core_slice_iter_IterMut_t (option LoadedEnclave_t))))
  :=
  t <-
    core_slice_iter_IterMut_Insts_CoreIterTraitsIteratorIteratorMutAT_next
      iter;
  let '(o, iter1, next_back) := t in
  match o with
  | None => Ok (Done (false, let im := next_back iter1 None in back im))
  | Some slot =>
    b <- core_option_Option_is_none slot;
    if b
    then
      Ok (Done (true,
        let im :=
          next_back iter1 (Some (Some
            {|
              loadedEnclave_descriptor := descriptor;
              loadedEnclave_start_address := address;
              loadedEnclave_efbs := efbs;
              loadedEnclave_efb_count := efb_count
            |}))
        in
        back im))
    else
      Ok (Cont (iter1,
        fun (im : core_slice_iter_IterMut_t (option LoadedEnclave_t)) =>
          let im1 := next_back im o in back im1))
  end
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::register_enclave]: loop 0:
    Source: 'src/lib.rs', lines 281:8-293:5
    Visibility: public *)
Definition enclaveSwapSpace_register_enclave_loop
  (iter : core_slice_iter_IterMut_t (option LoadedEnclave_t))
  (back : core_slice_iter_IterMut_t (option LoadedEnclave_t) ->
  core_slice_iter_IterMut_t (option LoadedEnclave_t))
  (descriptor : EnclaveDescriptor_t) (address : u32)
  (efbs : array EfbDescriptor_t 64%usize) (efb_count : usize) :
  result (bool * (core_slice_iter_IterMut_t (option LoadedEnclave_t)))
  :=
  loop
    (fun ((iter1, back1) : ((core_slice_iter_IterMut_t (option
      LoadedEnclave_t)) * (core_slice_iter_IterMut_t (option LoadedEnclave_t)
      -> core_slice_iter_IterMut_t (option LoadedEnclave_t)))) =>
      enclaveSwapSpace_register_enclave_loop_body descriptor address efbs
      efb_count iter1 back1)
    (iter, back)
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::register_enclave]:
    Source: 'src/lib.rs', lines 274:4-293:5
    Visibility: public *)
Definition enclaveSwapSpace_register_enclave
  (self : EnclaveSwapSpace_t) (descriptor : EnclaveDescriptor_t)
  (address : u32) (efbs : array EfbDescriptor_t 64%usize) (efb_count : usize) :
  result (bool * EnclaveSwapSpace_t)
  :=
  let (s, to_slice_mut_back) :=
    array_to_slice_mut self.(enclaveSwapSpace_loaded_enclaves)
  in
  p <- core_slice_Slice_iter_mut s;
  let (iter, iter_mut_back) := p in
  p1 <-
    enclaveSwapSpace_register_enclave_loop iter
      (fun (im : core_slice_iter_IterMut_t (option LoadedEnclave_t)) => im)
      descriptor address efbs efb_count;
  let (b, back) := p1 in
  let s1 := iter_mut_back back in
  let a := to_slice_mut_back s1 in
  Ok (b,
    {|
      enclaveSwapSpace_base_address := self.(enclaveSwapSpace_base_address);
      enclaveSwapSpace_size := self.(enclaveSwapSpace_size);
      enclaveSwapSpace_loaded_enclaves := a;
      enclaveSwapSpace_bitmap := self.(enclaveSwapSpace_bitmap)
    |})
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address::{impl core::ops::function::FnOnce<(u32,), core::option::Option<u32>> for umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address::closure<'_0>}::call_once]:
    Source: 'src/lib.rs', lines 305:42-305:76 *)
Definition
  EnclaveSwapSpace_get_block_address_closure_Insts_CoreOpsFunctionFnOnceTupleU32OptionU32_call_once
  (c : EnclaveSwapSpace_get_block_address_closure_t) (tupled_args : u32) :
  result (option u32)
  :=
  Ok (U32_checked_add c.(loadedEnclave_start_address) tupled_args)
.

(** Trait implementation: [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address::{impl core::ops::function::FnOnce<(u32,), core::option::Option<u32>> for umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address::closure<'_0>}]
    Source: 'src/lib.rs', lines 305:42-305:76 *)
Definition
  EnclaveSwapSpace_get_block_address_closure_Insts_CoreOpsFunctionFnOnceTupleU32OptionU32
  : core_ops_function_FnOnce_t EnclaveSwapSpace_get_block_address_closure_t u32
  (option u32) := {|
  core_ops_function_FnOnce_t_call_once :=
    EnclaveSwapSpace_get_block_address_closure_Insts_CoreOpsFunctionFnOnceTupleU32OptionU32_call_once;
|}.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-312:5
    Visibility: public *)
Definition enclaveSwapSpace_get_block_address_loop_body
  (enclave_id : u32) (block_id : u32)
  (iter : core_slice_iter_Iter_t (option LoadedEnclave_t)) :
  result (control_flow (core_slice_iter_Iter_t (option LoadedEnclave_t))
    (option u32))
  :=
  p <-
    core_slice_iter_Iter_Insts_CoreIterTraitsIteratorIteratorSharedAT_next
      iter;
  let (o, iter1) := p in
  match o with
  | None => Ok (Done None)
  | Some enc =>
    match enc with
    | None => Ok (Cont iter1)
    | Some e =>
      if e.(loadedEnclave_descriptor).(enclaveDescriptor_id) s= enclave_id
      then (
        i <- scalar_cast U32 Usize block_id;
        if i s< e.(loadedEnclave_efb_count)
        then (
          efb <- array_index_usize e.(loadedEnclave_efbs) i;
          if efb.(efbDescriptor_is_loaded)
          then
            if efb.(efbDescriptor_id) s= block_id
            then (
              let o1 := U32_checked_mul block_id sLOT_SIZE in
              o2 <-
                core_option_Option_and_then
                  EnclaveSwapSpace_get_block_address_closure_Insts_CoreOpsFunctionFnOnceTupleU32OptionU32
                  o1 e;
              Ok (Done o2))
            else Ok (Cont iter1)
          else Ok (Cont iter1))
        else Ok (Cont iter1))
      else Ok (Cont iter1)
    end
  end
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address]: loop 0:
    Source: 'src/lib.rs', lines 1:0-312:5
    Visibility: public *)
Definition enclaveSwapSpace_get_block_address_loop
  (iter : core_slice_iter_Iter_t (option LoadedEnclave_t)) (enclave_id : u32)
  (block_id : u32) :
  result (option u32)
  :=
  loop
    (fun (iter1 : core_slice_iter_Iter_t (option LoadedEnclave_t)) =>
      enclaveSwapSpace_get_block_address_loop_body enclave_id block_id iter1)
    iter
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address]:
    Source: 'src/lib.rs', lines 296:4-312:5
    Visibility: public *)
Definition enclaveSwapSpace_get_block_address
  (self : EnclaveSwapSpace_t) (enclave_id : u32) (block_id : u32) :
  result (option u32)
  :=
  let s := array_to_slice self.(enclaveSwapSpace_loaded_enclaves) in
  iter <- core_slice_Slice_iter s;
  enclaveSwapSpace_get_block_address_loop iter enclave_id block_id
.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::loaded_count]: loop body 0:
    Source: 'src/lib.rs', lines 322:8-327:9
    Visibility: public *)
Definition loadedEnclave_loaded_count_loop_body
  (self : LoadedEnclave_t) (count : usize) (i : usize) :
  result (control_flow (usize * usize) usize)
  :=
  if i s< self.(loadedEnclave_efb_count)
  then (
    ed <- array_index_usize self.(loadedEnclave_efbs) i;
    count1 <-
      if ed.(efbDescriptor_is_loaded)
      then usize_add count 1%usize
      else Ok count;
    i1 <- usize_add i 1%usize;
    Ok (Cont (count1, i1)))
  else Ok (Done count)
.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::loaded_count]: loop 0:
    Source: 'src/lib.rs', lines 322:8-327:9
    Visibility: public *)
Definition loadedEnclave_loaded_count_loop
  (self : LoadedEnclave_t) (count : usize) (i : usize) : result usize :=
  loop
    (fun ((count1, i1) : (usize * usize)) =>
      loadedEnclave_loaded_count_loop_body self count1 i1)
    (count, i)
.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::loaded_count]:
    Source: 'src/lib.rs', lines 316:4-329:5
    Visibility: public *)
Definition loadedEnclave_loaded_count
  (self : LoadedEnclave_t) : result usize :=
  loadedEnclave_loaded_count_loop self 0%usize 0%usize
.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim::{impl core::ops::function::FnOnce<((u32, u8),), u32> for umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim::closure}::call_once]:
    Source: 'src/lib.rs', lines 344:17-344:31 *)
Definition
  LoadedEnclave_find_eviction_victim_closure_Insts_CoreOpsFunctionFnOnceTuplePairU32U8U32_call_once
  (c : LoadedEnclave_find_eviction_victim_closure_t) (tupled_args : (u32 * u8))
  :
  result u32
  :=
  let (idx, _) := tupled_args in Ok idx
.

(** Trait implementation: [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim::{impl core::ops::function::FnOnce<((u32, u8),), u32> for umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim::closure}]
    Source: 'src/lib.rs', lines 344:17-344:31 *)
Definition
  LoadedEnclave_find_eviction_victim_closure_Insts_CoreOpsFunctionFnOnceTuplePairU32U8U32
  : core_ops_function_FnOnce_t LoadedEnclave_find_eviction_victim_closure_t
  (u32 * u8) u32 := {|
  core_ops_function_FnOnce_t_call_once :=
    LoadedEnclave_find_eviction_victim_closure_Insts_CoreOpsFunctionFnOnceTuplePairU32U8U32_call_once;
|}.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-343:9
    Visibility: public *)
Definition loadedEnclave_find_eviction_victim_loop_body
  (a : array EfbDescriptor_t 64%usize) (exclude_idx : u32)
  (iter : core_ops_range_Range usize) (best : option (u32 * u8)) :
  result (control_flow ((core_ops_range_Range usize) * (option (u32 * u8)))
    (option (u32 * u8)))
  :=
  p <-
    core_ops_range_Range_Insts_CoreIterTraitsIteratorIterator_next
      Usize_Insts_CoreIterRangeStep iter;
  let (o, iter1) := p in
  match o with
  | None => Ok (Done best)
  | Some i =>
    efb <- array_index_usize a i;
    if efb.(efbDescriptor_is_loaded)
    then (
      i1 <- scalar_cast Usize U32 i;
      if i1 s<> exclude_idx
      then
        match best with
        | None => Ok (Cont (iter1, Some (i1, efb.(efbDescriptor_counter))))
        | Some p1 =>
          let (_, bc) := p1 in
          if efb.(efbDescriptor_counter) s< bc
          then Ok (Cont (iter1, Some (i1, efb.(efbDescriptor_counter))))
          else Ok (Cont (iter1, best))
        end
      else Ok (Cont (iter1, best)))
    else Ok (Cont (iter1, best))
  end
.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim]: loop 0:
    Source: 'src/lib.rs', lines 1:0-343:9
    Visibility: public *)
Definition loadedEnclave_find_eviction_victim_loop
  (iter : core_ops_range_Range usize) (a : array EfbDescriptor_t 64%usize)
  (exclude_idx : u32) (best : option (u32 * u8)) :
  result (option (u32 * u8))
  :=
  loop
    (fun ((iter1, best1) : ((core_ops_range_Range usize) * (option (u32 *
      u8)))) => loadedEnclave_find_eviction_victim_loop_body a exclude_idx
      iter1 best1)
    (iter, best)
.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim]:
    Source: 'src/lib.rs', lines 331:4-345:5
    Visibility: public *)
Definition loadedEnclave_find_eviction_victim
  (self : LoadedEnclave_t) (exclude_idx : u32) : result (option u32) :=
  best <-
    loadedEnclave_find_eviction_victim_loop
      {|
        core_ops_range_Range_start := 1%usize;
        core_ops_range_Range_end_ := self.(loadedEnclave_efb_count)
      |} self.(loadedEnclave_efbs) exclude_idx None;
  core_option_Option_map
    LoadedEnclave_find_eviction_victim_closure_Insts_CoreOpsFunctionFnOnceTuplePairU32U8U32
    best tt
.

End Ess_Funs.
