(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_ess_core]: external types.
-- This is a template file: rename it to "TypesExternal.v" and fill the holes. *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Ess_TypesExternal_Template.

(** [core::fmt::Arguments]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 716:0-716:24
    Name pattern: [core::fmt::Arguments]
    Visibility: public *)
Axiom core_fmt_Arguments_t : Type.

(** [core::slice::iter::IterMut]
    Source: '/rustc/library/core/src/slice/iter.rs', lines 192:0-192:29
    Name pattern: [core::slice::iter::IterMut]
    Visibility: public *)
Axiom core_slice_iter_IterMut_t : forall (T : Type), Type.

(** [core::slice::iter::Iter]
    Source: '/rustc/library/core/src/slice/iter.rs', lines 67:0-67:26
    Name pattern: [core::slice::iter::Iter]
    Visibility: public *)
Axiom core_slice_iter_Iter_t : forall (T : Type), Type.

End Ess_TypesExternal_Template.
