(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_ess_core]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Ess_TypesExternal.
Include Ess_TypesExternal.
Module Ess_Types.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 250:0-250:65
    Name pattern: [core::cmp::PartialEq]
    Visibility: public *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.

(** [core::cmp::Ordering]
    Source: '/rustc/library/core/src/cmp.rs', lines 405:0-405:17
    Name pattern: [core::cmp::Ordering]
    Visibility: public *)
Inductive core_cmp_Ordering_t :=
| Core_cmp_Ordering_Less : core_cmp_Ordering_t
| Core_cmp_Ordering_Equal : core_cmp_Ordering_t
| Core_cmp_Ordering_Greater : core_cmp_Ordering_t
.

(** Trait declaration: [core::cmp::PartialOrd]
    Source: '/rustc/library/core/src/cmp.rs', lines 1366:0-1367:41
    Name pattern: [core::cmp::PartialOrd]
    Visibility: public *)
Record core_cmp_PartialOrd_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialOrd_t {
  core_cmp_PartialOrd_tcore_cmp_PartialOrd_t_PartialEqInst :
    core_cmp_PartialEq_t Self Rhs;
  core_cmp_PartialOrd_t_partial_cmp : Self -> Rhs -> result (option
    core_cmp_Ordering_t);
}.

Arguments mkcore_cmp_PartialOrd_t { _ } { _ }.
Arguments core_cmp_PartialOrd_tcore_cmp_PartialOrd_t_PartialEqInst { _ } { _ }
  _.
Arguments core_cmp_PartialOrd_t_partial_cmp { _ } { _ } _.

(** [core::convert::Infallible]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 930:0-930:19
    Name pattern: [core::convert::Infallible]
    Visibility: public *)
Inductive core_convert_Infallible_t :=.

(** Trait declaration: [core::default::Default]
    Source: '/rustc/library/core/src/default.rs', lines 107:0-107:30
    Name pattern: [core::default::Default]
    Visibility: public *)
Record core_default_Default_t (Self : Type) := mkcore_default_Default_t {
  core_default_Default_t_default : result Self;
}.

Arguments mkcore_default_Default_t { _ }.
Arguments core_default_Default_t_default { _ } _.

(** Trait declaration: [core::iter::range::Step]
    Source: '/rustc/library/core/src/iter/range.rs', lines 34:0-34:64
    Name pattern: [core::iter::range::Step]
    Visibility: public *)
Record core_iter_range_Step_t (Self : Type) := mkcore_iter_range_Step_t {
  core_iter_range_Step_tcore_iter_range_Step_t_cloneCloneInst :
    core_clone_Clone Self;
  core_iter_range_Step_tcore_iter_range_Step_t_cmpPartialOrdInst :
    core_cmp_PartialOrd_t Self Self;
  core_iter_range_Step_t_steps_between : Self -> Self -> result (usize *
    (option usize));
  core_iter_range_Step_t_forward_checked : Self -> usize -> result (option
    Self);
  core_iter_range_Step_t_backward_checked : Self -> usize -> result (option
    Self);
}.

Arguments mkcore_iter_range_Step_t { _ }.
Arguments core_iter_range_Step_tcore_iter_range_Step_t_cloneCloneInst { _ } _.
Arguments core_iter_range_Step_tcore_iter_range_Step_t_cmpPartialOrdInst { _ }
  _.
Arguments core_iter_range_Step_t_steps_between { _ } _.
Arguments core_iter_range_Step_t_forward_checked { _ } _.
Arguments core_iter_range_Step_t_backward_checked { _ } _.

(** Trait declaration: [core::iter::traits::iterator::Iterator]
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 42:0-42:24
    Name pattern: [core::iter::traits::iterator::Iterator]
    Visibility: public *)
Record core_iter_traits_iterator_Iterator_t (Self : Type) (Self_Item : Type)
  := mkcore_iter_traits_iterator_Iterator_t {
  core_iter_traits_iterator_Iterator_t_next : Self -> result ((option
    Self_Item) * Self);
}.

Arguments mkcore_iter_traits_iterator_Iterator_t { _ } { _ }.
Arguments core_iter_traits_iterator_Iterator_t_next { _ } { _ } _.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 89:0-89:31
    Name pattern: [core::ops::control_flow::ControlFlow]
    Visibility: public *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** Trait declaration: [core::ops::function::FnOnce]
    Source: '/rustc/library/core/src/ops/function.rs', lines 242:0-242:35
    Name pattern: [core::ops::function::FnOnce]
    Visibility: public *)
Record core_ops_function_FnOnce_t (Self : Type) (Args : Type) (Self_Output :
  Type) := mkcore_ops_function_FnOnce_t {
  core_ops_function_FnOnce_t_call_once : Self -> Args -> result Self_Output;
}.

Arguments mkcore_ops_function_FnOnce_t { _ } { _ } { _ }.
Arguments core_ops_function_FnOnce_t_call_once { _ } { _ } { _ } _.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 557:0-557:21
    Name pattern: [core::result::Result]
    Visibility: public *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [umbra_error::UmbraError]
    Source: '/Users/salvatorebramante/Downloads/umbra/crates/umbra-error/src/lib.rs', lines 32:0-32:19
    Name pattern: [umbra_error::UmbraError]
    Visibility: public *)
Inductive umbra_error_UmbraError_t :=
| Umbra_error_UmbraError_NscArgInvalid : str -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_EnclaveNotFound : u32 -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_EnclaveAlreadyLoaded : u32 -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_EnclaveStateInvalid : umbra_error_UmbraError_t
| Umbra_error_UmbraError_MeasurementMismatch :
  array u8 8%usize ->
  array u8 8%usize ->
  umbra_error_UmbraError_t
| Umbra_error_UmbraError_HashHardware : umbra_error_UmbraError_t
| Umbra_error_UmbraError_AesHardware : umbra_error_UmbraError_t
| Umbra_error_UmbraError_KeyDerivation : umbra_error_UmbraError_t
| Umbra_error_UmbraError_DmaTimeout : umbra_error_UmbraError_t
| Umbra_error_UmbraError_EssRegionExhausted : umbra_error_UmbraError_t
| Umbra_error_UmbraError_MemProtectDenied : u32 -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_OffsetOverflow : umbra_error_UmbraError_t
| Umbra_error_UmbraError_LengthMismatch : umbra_error_UmbraError_t
| Umbra_error_UmbraError_InternalInvariant : str -> umbra_error_UmbraError_t
.

(** [umbra_ess_core::EnclaveDescriptor]
    Source: 'src/lib.rs', lines 119:0-126:1
    Visibility: public *)
Record EnclaveDescriptor_t :=
mkEnclaveDescriptor_t {
  enclaveDescriptor_id : u32;
  enclaveDescriptor_flash_base : u32;
  enclaveDescriptor_ram_base : u32;
  enclaveDescriptor_code_size : u32;
  enclaveDescriptor_entry_point : u32;
  enclaveDescriptor_is_loaded : bool;
}
.

(** [umbra_ess_core::EfbDescriptor]
    Source: 'src/lib.rs', lines 154:0-160:1
    Visibility: public *)
Record EfbDescriptor_t :=
mkEfbDescriptor_t {
  efbDescriptor_id : u32;
  efbDescriptor_is_loaded : bool;
  efbDescriptor_counter : u8;
  efbDescriptor_reachable : array u8 4%usize;
  efbDescriptor_reachable_count : u8;
}
.

(** [umbra_ess_core::LoadedEnclave]
    Source: 'src/lib.rs', lines 175:0-180:1
    Visibility: public *)
Record LoadedEnclave_t :=
mkLoadedEnclave_t {
  loadedEnclave_descriptor : EnclaveDescriptor_t;
  loadedEnclave_start_address : u32;
  loadedEnclave_efbs : array EfbDescriptor_t 64%usize;
  loadedEnclave_efb_count : usize;
}
.

(** [umbra_ess_core::EnclaveSwapSpace]
    Source: 'src/lib.rs', lines 146:0-151:1
    Visibility: public *)
Record EnclaveSwapSpace_t :=
mkEnclaveSwapSpace_t {
  enclaveSwapSpace_base_address : u32;
  enclaveSwapSpace_size : u32;
  enclaveSwapSpace_loaded_enclaves : array (option LoadedEnclave_t) 2%usize;
  enclaveSwapSpace_bitmap : array u32 8%usize;
}
.

(** [umbra_ess_core::{umbra_ess_core::EnclaveSwapSpace}::get_block_address::closure]
    Source: 'src/lib.rs', lines 305:42-305:76 *)
Definition EnclaveSwapSpace_get_block_address_closure_t : Type :=
  LoadedEnclave_t
.

(** [umbra_ess_core::{umbra_ess_core::LoadedEnclave}::find_eviction_victim::closure]
    Source: 'src/lib.rs', lines 344:17-344:31 *)
Definition LoadedEnclave_find_eviction_victim_closure_t : Type := unit.

End Ess_Types.
