(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_rot_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes. *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Rot_Types.
Include Rot_Types.
Module Rot_FunsExternal_Template.

(** [core::cmp::min]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1574:0-1574:70
    Name pattern: [core::cmp::min]
    Visibility: public *)
Axiom core_cmp_min :
  forall{T : Type} (ordInst : core_cmp_Ord_t T), T -> T -> result T
.

(** [core::cmp::impls::{impl core::cmp::PartialEq<usize> for usize}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1878:16-1878:50
    Name pattern: [core::cmp::impls::{core::cmp::PartialEq<usize, usize>}::eq]
    Visibility: public *)
Axiom Usize_Insts_CoreCmpPartialEqUsize_eq : usize -> usize -> result bool.

(** [core::cmp::impls::{impl core::cmp::PartialOrd<usize> for usize}::partial_cmp]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1999:16-1999:71
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<usize, usize>}::partial_cmp]
    Visibility: public *)
Axiom Usize_Insts_CoreCmpPartialOrdUsize_partial_cmp
  : usize -> usize -> result (option core_cmp_Ordering_t)
.

(** [core::cmp::impls::{impl core::cmp::Ord for usize}::cmp]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2010:16-2010:55
    Name pattern: [core::cmp::impls::{core::cmp::Ord<usize>}::cmp]
    Visibility: public *)
Axiom Usize_Insts_CoreCmpOrd_cmp : usize -> usize -> result core_cmp_Ordering_t
.

(** [core::convert::{impl core::convert::From<T> for T}::from]:
    Source: '/rustc/library/core/src/convert/mod.rs', lines 788:4-788:22
    Name pattern: [core::convert::{core::convert::From<@T, @T>}::from]
    Visibility: public *)
Axiom core_convert_From_Blanket_from : forall{T : Type}, T -> result T.

(** [core::result::{impl core::ops::try_trait::Try for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2177:4-2177:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch]
    Visibility: public *)
Axiom core_result_Result_Insts_CoreOpsTry_traitTry_branch :
  forall{T : Type} {E : Type},
        core_result_Result_t T E -> result (core_ops_control_flow_ControlFlow_t
          (core_result_Result_t core_convert_Infallible_t E) T)
.

(** [core::result::{impl core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2192:4-2192:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public *)
Axiom
  core_result_Result_Insts_CoreOpsTry_traitFromResidualResultInfallibleE_from_residual
  :
  forall(T : Type) {E : Type} {F : Type} (convertFromInst : core_convert_From F
        E),
        core_result_Result_t core_convert_Infallible_t E -> result
          (core_result_Result_t T F)
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::index_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 533:4-533:51
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::index_mut]
    Visibility: public *)
Axiom
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index_mut
  :
  forall{T : Type},
        core_ops_range_RangeTo usize -> slice T -> result ((slice T) * (slice T
          -> slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::index]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 528:4-528:39
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::index]
    Visibility: public *)
Axiom
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index :
  forall{T : Type}, core_ops_range_RangeTo usize -> slice T -> result (slice T)
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get_unchecked_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 522:4-522:66
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get_unchecked_mut]
    Visibility: public *)
Axiom
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked_mut
  :
  forall{T : Type},
        core_ops_range_RangeTo usize -> mut_raw_ptr (slice T) -> result
          (mut_raw_ptr (slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get_unchecked]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 516:4-516:66
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get_unchecked]
    Visibility: public *)
Axiom
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked
  :
  forall{T : Type},
        core_ops_range_RangeTo usize -> const_raw_ptr (slice T) -> result
          (const_raw_ptr (slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 511:4-511:57
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get_mut]
    Visibility: public *)
Axiom
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_mut
  :
  forall{T : Type},
        core_ops_range_RangeTo usize -> slice T -> result ((option (slice T)) *
          (option (slice T) -> slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 506:4-506:45
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get]
    Visibility: public *)
Axiom core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get
  :
  forall{T : Type},
        core_ops_range_RangeTo usize -> slice T -> result (option (slice T))
.

(** [core::slice::{[T]}::copy_from_slice]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 4321:4-4323:16
    Name pattern: [core::slice::{[@T]}::copy_from_slice]
    Visibility: public *)
Axiom core_slice_Slice_copy_from_slice :
  forall{T : Type} (markerCopyInst : core_marker_Copy T),
        slice T -> slice T -> result (slice T)
.

End Rot_FunsExternal_Template.
