(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_rot_core]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Rot_Types.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 250:0-250:65
    Name pattern: [core::cmp::PartialEq]
    Visibility: public *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.

(** Trait declaration: [core::cmp::Eq]
    Source: '/rustc/library/core/src/cmp.rs', lines 338:0-338:58
    Name pattern: [core::cmp::Eq]
    Visibility: public *)
Record core_cmp_Eq_t (Self : Type) := mkcore_cmp_Eq_t {
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst : core_cmp_PartialEq_t Self Self;
}.

Arguments mkcore_cmp_Eq_t { _ }.
Arguments core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst { _ } _.

(** [core::cmp::Ordering]
    Source: '/rustc/library/core/src/cmp.rs', lines 405:0-405:17
    Name pattern: [core::cmp::Ordering]
    Visibility: public *)
Inductive core_cmp_Ordering_t :=
| Core_cmp_Ordering_Less : core_cmp_Ordering_t
| Core_cmp_Ordering_Equal : core_cmp_Ordering_t
| Core_cmp_Ordering_Greater : core_cmp_Ordering_t
.

(** Trait declaration: [core::cmp::PartialOrd]
    Source: '/rustc/library/core/src/cmp.rs', lines 1366:0-1367:41
    Name pattern: [core::cmp::PartialOrd]
    Visibility: public *)
Record core_cmp_PartialOrd_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialOrd_t {
  core_cmp_PartialOrd_tcore_cmp_PartialOrd_t_PartialEqInst :
    core_cmp_PartialEq_t Self Rhs;
  core_cmp_PartialOrd_t_partial_cmp : Self -> Rhs -> result (option
    core_cmp_Ordering_t);
}.

Arguments mkcore_cmp_PartialOrd_t { _ } { _ }.
Arguments core_cmp_PartialOrd_tcore_cmp_PartialOrd_t_PartialEqInst { _ } { _ }
  _.
Arguments core_cmp_PartialOrd_t_partial_cmp { _ } { _ } _.

(** Trait declaration: [core::cmp::Ord]
    Source: '/rustc/library/core/src/cmp.rs', lines 982:0-982:73
    Name pattern: [core::cmp::Ord]
    Visibility: public *)
Record core_cmp_Ord_t (Self : Type) := mkcore_cmp_Ord_t {
  core_cmp_Ord_tcore_cmp_Ord_t_EqInst : core_cmp_Eq_t Self;
  core_cmp_Ord_tcore_cmp_Ord_t_PartialOrdInst : core_cmp_PartialOrd_t Self
    Self;
  core_cmp_Ord_t_cmp : Self -> Self -> result core_cmp_Ordering_t;
}.

Arguments mkcore_cmp_Ord_t { _ }.
Arguments core_cmp_Ord_tcore_cmp_Ord_t_EqInst { _ } _.
Arguments core_cmp_Ord_tcore_cmp_Ord_t_PartialOrdInst { _ } _.
Arguments core_cmp_Ord_t_cmp { _ } _.

(** [core::convert::Infallible]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 930:0-930:19
    Name pattern: [core::convert::Infallible]
    Visibility: public *)
Inductive core_convert_Infallible_t :=.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 89:0-89:31
    Name pattern: [core::ops::control_flow::ControlFlow]
    Visibility: public *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 557:0-557:21
    Name pattern: [core::result::Result]
    Visibility: public *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [umbra_error::UmbraError]
    Source: 'crates/umbra-error/src/lib.rs', lines 32:0-32:19
    Name pattern: [umbra_error::UmbraError]
    Visibility: public *)
Inductive umbra_error_UmbraError_t :=
| Umbra_error_UmbraError_NscArgInvalid : str -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_EnclaveNotFound : u32 -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_EnclaveAlreadyLoaded : u32 -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_EnclaveStateInvalid : umbra_error_UmbraError_t
| Umbra_error_UmbraError_MeasurementMismatch :
  array u8 8%usize ->
  array u8 8%usize ->
  umbra_error_UmbraError_t
| Umbra_error_UmbraError_HashHardware : umbra_error_UmbraError_t
| Umbra_error_UmbraError_AesHardware : umbra_error_UmbraError_t
| Umbra_error_UmbraError_KeyDerivation : umbra_error_UmbraError_t
| Umbra_error_UmbraError_DmaTimeout : umbra_error_UmbraError_t
| Umbra_error_UmbraError_EssRegionExhausted : umbra_error_UmbraError_t
| Umbra_error_UmbraError_MemProtectDenied : u32 -> umbra_error_UmbraError_t
| Umbra_error_UmbraError_OffsetOverflow : umbra_error_UmbraError_t
| Umbra_error_UmbraError_LengthMismatch : umbra_error_UmbraError_t
| Umbra_error_UmbraError_InternalInvariant : str -> umbra_error_UmbraError_t
.

(** Trait declaration: [umbra_api::crypto::CryptoEngine]
    Source: 'crates/umbra-api/src/crypto.rs', lines 10:0-10:22
    Name pattern: [umbra_api::crypto::CryptoEngine]
    Visibility: public *)
Record umbra_api_crypto_CryptoEngine_t (Self : Type)
  := mkumbra_api_crypto_CryptoEngine_t {
  umbra_api_crypto_CryptoEngine_t_hmac : Self -> slice u8 -> slice u8 -> slice
    u8 -> result ((core_result_Result_t unit umbra_error_UmbraError_t) * Self *
    (slice u8));
  umbra_api_crypto_CryptoEngine_t_hash : Self -> slice u8 -> slice u8 -> result
    ((core_result_Result_t unit umbra_error_UmbraError_t) * Self * (slice u8));
  umbra_api_crypto_CryptoEngine_t_aes_decrypt : Self -> slice u8 -> slice u8 ->
    slice u8 -> result ((core_result_Result_t unit umbra_error_UmbraError_t) *
    Self * (slice u8));
}.

Arguments mkumbra_api_crypto_CryptoEngine_t { _ }.
Arguments umbra_api_crypto_CryptoEngine_t_hmac { _ } _.
Arguments umbra_api_crypto_CryptoEngine_t_hash { _ } _.
Arguments umbra_api_crypto_CryptoEngine_t_aes_decrypt { _ } _.

(** [umbra_rot_core::Key]
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 32:0-34:1
    Visibility: public *)
Record Key_t := mkKey_t { key_value : array u8 32%usize; }.

End Rot_Types.
