(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_rot_core]: function definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Rot_Types.
Include Rot_Types.
Require Import Rot_FunsExternal.
Include Rot_FunsExternal.
Module Rot_Funs.

(** Trait implementation: [core::convert::{impl core::convert::From<T> for T}]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 785:0-785:27
    Name pattern: [core::convert::From<@T, @T>] *)
Definition core_convert_From_Blanket (T : Type) : core_convert_From T T := {|
  from_ := core_convert_From_Blanket_from;
|}.

(** Trait implementation: [core::slice::index::private_slice_index::{impl core::slice::index::private_slice_index::Sealed for core::ops::range::RangeTo<usize>}]
    Source: '/rustc/library/core/src/slice/index.rs', lines 116:4-116:39
    Name pattern: [core::slice::index::private_slice_index::Sealed<core::ops::range::RangeTo<usize>>] *)
Definition
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexPrivate_slice_indexSealed :
  core_slice_index_private_slice_index_Sealed (core_ops_range_RangeTo usize)
  := mkcore_slice_index_private_slice_index_Sealed.

(** Trait implementation: [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}]
    Source: '/rustc/library/core/src/slice/index.rs', lines 502:0-502:60
    Name pattern: [core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>] *)
Definition core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
  (T : Type) : core_slice_index_SliceIndex (core_ops_range_RangeTo usize)
  (slice T) (slice T) := {|
  sealedInst :=
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexPrivate_slice_indexSealed;
  core_slice_index_SliceIndex_get :=
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get;
  core_slice_index_SliceIndex_get_mut :=
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_mut;
  core_slice_index_SliceIndex_get_unchecked :=
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked;
  core_slice_index_SliceIndex_get_unchecked_mut :=
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked_mut;
  core_slice_index_SliceIndex_index :=
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index;
  core_slice_index_SliceIndex_index_mut :=
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index_mut;
|}.

(** [umbra_rot_core::KEY_SIZE]
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 28:0-28:31
    Visibility: public *)
Definition kEY_SIZE : usize := 32%usize.

(** [umbra_rot_core::{impl core::clone::Clone for umbra_rot_core::Key}::clone]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 31:15-31:20
    Visibility: public *)
Definition Key_Insts_CoreCloneClone_clone (self : Key_t) : result Key_t :=
  Ok self
.

(** Trait implementation: [umbra_rot_core::{impl core::clone::Clone for umbra_rot_core::Key}]
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 31:15-31:20 *)
Definition Key_Insts_CoreCloneClone : core_clone_Clone Key_t := {|
  core_clone_Clone_clone := Key_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [umbra_rot_core::{impl core::marker::Copy for umbra_rot_core::Key}]
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 31:9-31:13 *)
Definition Key_Insts_CoreMarkerCopy : core_marker_Copy Key_t := {|
  cloneInst := Key_Insts_CoreCloneClone;
|}.

(** [umbra_rot_core::{umbra_rot_core::Key}::new]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 37:4-39:5
    Visibility: public *)
Definition key_new (value : array u8 32%usize) : result Key_t :=
  Ok {| key_value := value |}
.

(** [umbra_rot_core::{umbra_rot_core::Key}::zero]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 41:4-45:5
    Visibility: public *)
Definition key_zero : result Key_t :=
  let a := array_repeat 32%usize 0%u8 in Ok {| key_value := a |}
.

(** [umbra_rot_core::verify_measurement]: loop body 0:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 57:4-60:5
    Visibility: public *)
Definition verify_measurement_loop_body
  (measured_hash : slice u8) (expected_hash : slice u8) (diff : u8) (i : usize)
  :
  result (control_flow (u8 * usize) u8)
  :=
  let i1 := slice_len measured_hash in
  if i s< i1
  then (
    i2 <- slice_index_usize measured_hash i;
    i3 <- slice_index_usize expected_hash i;
    let i4 := u8_xor i2 i3 in
    let diff1 := u8_or diff i4 in
    i5 <- usize_add i 1%usize;
    Ok (Cont (diff1, i5)))
  else Ok (Done diff)
.

(** [umbra_rot_core::verify_measurement]: loop 0:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 57:4-60:5
    Visibility: public *)
Definition verify_measurement_loop
  (measured_hash : slice u8) (expected_hash : slice u8) (diff : u8) (i : usize)
  :
  result u8
  :=
  loop
    (fun ((diff1, i1) : (u8 * usize)) => verify_measurement_loop_body
      measured_hash expected_hash diff1 i1)
    (diff, i)
.

(** [umbra_rot_core::verify_measurement]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 51:0-62:1
    Visibility: public *)
Definition verify_measurement
  (measured_hash : slice u8) (expected_hash : slice u8) : result bool :=
  let i := slice_len measured_hash in
  let i1 := slice_len expected_hash in
  if i s<> i1
  then Ok false
  else (
    diff <- verify_measurement_loop measured_hash expected_hash 0%u8 0%usize;
    Ok (diff s= 0%u8))
.

(** [umbra_rot_core::derive_key]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 65:0-73:1
    Visibility: public *)
Definition derive_key
  {C : Type} (umbra_apicryptoCryptoEngineInst : umbra_api_crypto_CryptoEngine_t
  C) (crypto : C) (base_key : Key_t) (context : slice u8) :
  result ((core_result_Result_t Key_t umbra_error_UmbraError_t) * C)
  :=
  let new_key_bytes := array_repeat 32%usize 0%u8 in
  let s := array_to_slice base_key.(key_value) in
  let (s1, to_slice_mut_back) := array_to_slice_mut new_key_bytes in
  t <-
    umbra_apicryptoCryptoEngineInst.(umbra_api_crypto_CryptoEngine_t_hmac)
      crypto s context s1;
  let '(r, crypto1, s2) := t in
  cf <- core_result_Result_Insts_CoreOpsTry_traitTry_branch r;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue _ =>
    let new_key_bytes1 := to_slice_mut_back s2 in
    k <- key_new new_key_bytes1;
    Ok (Core_result_Result_Ok k, crypto1)
  | Core_ops_control_flow_ControlFlow_Break residual =>
    r1 <-
      core_result_Result_Insts_CoreOpsTry_traitFromResidualResultInfallibleE_from_residual
        Key_t (core_convert_From_Blanket umbra_error_UmbraError_t) residual;
    Ok (r1, crypto1)
  end
.

(** [umbra_rot_core::update_chain]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 78:0-87:1
    Visibility: public *)
Definition update_chain
  {C : Type} (umbra_apicryptoCryptoEngineInst : umbra_api_crypto_CryptoEngine_t
  C) (crypto : C) (current_key : array u8 32%usize) (block : slice u8) :
  result ((core_result_Result_t unit umbra_error_UmbraError_t) * C * (array u8
    32%usize))
  :=
  let output := array_repeat 32%usize 0%u8 in
  let s := array_to_slice current_key in
  let (s1, to_slice_mut_back) := array_to_slice_mut output in
  t <-
    umbra_apicryptoCryptoEngineInst.(umbra_api_crypto_CryptoEngine_t_hmac)
      crypto s block s1;
  let '(r, crypto1, s2) := t in
  cf <- core_result_Result_Insts_CoreOpsTry_traitTry_branch r;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue _ =>
    let output1 := to_slice_mut_back s2 in
    Ok (Core_result_Result_Ok tt, crypto1, output1)
  | Core_ops_control_flow_ControlFlow_Break residual =>
    r1 <-
      core_result_Result_Insts_CoreOpsTry_traitFromResidualResultInfallibleE_from_residual
        unit (core_convert_From_Blanket umbra_error_UmbraError_t) residual;
    Ok (r1, crypto1, current_key)
  end
.

(** [umbra_rot_core::validate_block]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 104:0-114:1
    Visibility: public *)
Definition validate_block
  {C : Type} (umbra_apicryptoCryptoEngineInst : umbra_api_crypto_CryptoEngine_t
  C) (crypto : C) (data : slice u8) (expected_measurement : Key_t) :
  result (bool * C)
  :=
  base_key <- key_zero;
  p <- derive_key umbra_apicryptoCryptoEngineInst crypto base_key data;
  let (r, crypto1) := p in
  match r with
  | Core_result_Result_Ok computed =>
    let s := array_to_slice computed.(key_value) in
    let s1 := array_to_slice expected_measurement.(key_value) in
    b <- verify_measurement s s1;
    Ok (b, crypto1)
  | Core_result_Result_Err _ => Ok (false, crypto1)
  end
.

(** [umbra_rot_core::authenticate_and_decrypt]:
    Source: 'crates/umbra-rot-core/src/lib.rs', lines 119:0-138:1
    Visibility: public *)
Definition authenticate_and_decrypt
  {C : Type} (umbra_apicryptoCryptoEngineInst : umbra_api_crypto_CryptoEngine_t
  C) (crypto : C) (key : Key_t) (data : slice u8) (expected_hmac : slice u8) :
  result ((core_result_Result_t unit umbra_error_UmbraError_t) * C * (slice
    u8))
  :=
  p <- derive_key umbra_apicryptoCryptoEngineInst crypto key data;
  let (r, crypto1) := p in
  cf <- core_result_Result_Insts_CoreOpsTry_traitTry_branch r;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue val =>
    let s := array_to_slice val.(key_value) in
    b <- verify_measurement s expected_hmac;
    if b
    then (
      let iv := array_repeat 16%usize 0%u8 in
      let s1 := array_to_slice key.(key_value) in
      let s2 := array_to_slice iv in
      t <-
        umbra_apicryptoCryptoEngineInst.(umbra_api_crypto_CryptoEngine_t_aes_decrypt)
          crypto1 s1 s2 data;
      let '(r1, crypto2, data1) := t in
      cf1 <- core_result_Result_Insts_CoreOpsTry_traitTry_branch r1;
      match cf1 with
      | Core_ops_control_flow_ControlFlow_Continue _ =>
        Ok (Core_result_Result_Ok tt, crypto2, data1)
      | Core_ops_control_flow_ControlFlow_Break residual =>
        r2 <-
          core_result_Result_Insts_CoreOpsTry_traitFromResidualResultInfallibleE_from_residual
            unit (core_convert_From_Blanket umbra_error_UmbraError_t) residual;
        Ok (r2, crypto2, data1)
      end)
    else (
      let expected := array_repeat 8%usize 0%u8 in
      let got := array_repeat 8%usize 0%u8 in
      let i := slice_len expected_hmac in
      elen <- core_cmp_min core_cmp_OrdUsize 8%usize i;
      p1 <-
        core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
          (core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
          u8)) expected {| core_ops_range_RangeTo_end_ := elen |};
      let (s1, index_mut_back) := p1 in
      s2 <-
        core_slice_index_Slice_index
          (core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
          u8) expected_hmac {| core_ops_range_RangeTo_end_ := elen |};
      s3 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s1 s2;
      let s4 := array_to_slice val.(key_value) in
      let i1 := slice_len s4 in
      glen <- core_cmp_min core_cmp_OrdUsize 8%usize i1;
      p2 <-
        core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
          (core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
          u8)) got {| core_ops_range_RangeTo_end_ := glen |};
      let (s5, index_mut_back1) := p2 in
      s6 <-
        core_array_Array_index (core_ops_index_IndexSliceInst
          (core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
          u8)) val.(key_value) {| core_ops_range_RangeTo_end_ := glen |};
      s7 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s5 s6;
      let expected1 := index_mut_back s3 in
      let got1 := index_mut_back1 s7 in
      Ok (Core_result_Result_Err (Umbra_error_UmbraError_MeasurementMismatch
        expected1 got1), crypto1, data))
  | Core_ops_control_flow_ControlFlow_Break residual =>
    r1 <-
      core_result_Result_Insts_CoreOpsTry_traitFromResidualResultInfallibleE_from_residual
        unit (core_convert_From_Blanket umbra_error_UmbraError_t) residual;
    Ok (r1, crypto1, data)
  end
.

End Rot_Funs.
