// Auto-generated by tools/measure_blobs.py — DO NOT EDIT.
// Boot-time chained-HMAC constants. The FSBL's
// `measure_boot_blobs()` recomputes these chains over the flashed
// regions and halts boot on mismatch.

pub const MODEL_BYTECODE_ADDR: u32 = 0x7020_0000;
pub const MODEL_BYTECODE_LEN: u32 = 46304;
pub const MODEL_BYTECODE_HMAC: [u8; 32] = [78, 108, 1, 143, 50, 18, 151, 218, 93, 28, 86, 149, 195, 170, 50, 142, 211, 35, 140, 244, 15, 223, 95, 19, 211, 16, 74, 72, 228, 69, 35, 183];

pub const MODEL_WEIGHTS_ADDR: u32 = 0x7038_0000;
pub const MODEL_WEIGHTS_LEN: u32 = 11064305;
pub const MODEL_WEIGHTS_HMAC: [u8; 32] = [23, 85, 105, 100, 187, 162, 1, 86, 16, 195, 221, 189, 118, 222, 0, 65, 98, 150, 182, 56, 110, 75, 192, 88, 204, 190, 3, 223, 250, 51, 76, 135];
