(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_update_core]: function definitions *)
Require Import Primitives.
Import Primitives.
Require Import AeneasLoopShim.
Import AeneasLoopShim.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Update_Types.
Include Update_Types.
Require Import Update_FunsExternal.
Include Update_FunsExternal.
Module Update_Funs.

(** [umbra_update_core::UPDATE_MAGIC]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 21:0-21:42
    Visibility: public *)
Definition uPDATE_MAGIC : u32 := 827348309%u32.

(** [umbra_update_core::PKG_TAG_LABEL]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 26:0-26:52
    Visibility: public *)
Definition pKG_TAG_LABEL : slice u8 :=
  array_to_slice
    (mk_array15 117%u8 109%u8 98%u8 114%u8 97%u8 45%u8 117%u8 112%u8 100%u8 97%u8 116%u8 101%u8 45%u8 118%u8 50%u8)
.

(** [umbra_update_core::PKG_PREIMAGE_LEN]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 32:0-32:39
    Visibility: public *)
Definition pKG_PREIMAGE_LEN : usize := 91%usize.

(** [umbra_update_core::HDR_LEN]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 34:0-34:30
    Visibility: public *)
Definition hDR_LEN : usize := 48%usize.

(** [umbra_update_core::FIXED_PREFIX]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 35:0-35:31 *)
Definition fIXED_PREFIX : usize := 32%usize.

(** [umbra_update_core::MIN_BLOB]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 36:0-36:32 *)
Definition mIN_BLOB : usize := hDR_LEN.

(** [umbra_update_core::compute_pkg_tag]:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 70:0-87:1
    Visibility: public *)
Definition compute_pkg_tag
  {H : Type} (pkgHmacInst : PkgHmac_t H) (nonce : array u8 16%usize)
  (author_id : u32) (version : u32) (blob_len : u32)
  (header : array u8 48%usize) (h : H) (key : slice u8) :
  result (array u8 32%usize)
  :=
  let pre := array_repeat 91%usize 0%u8 in
  p <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre
      {|
        core_ops_range_Range_start := 0%usize;
        core_ops_range_Range_end_ := 15%usize
      |};
  let (s, index_mut_back) := p in
  s1 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s pKG_TAG_LABEL;
  let pre1 := index_mut_back s1 in
  p1 <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre1
      {|
        core_ops_range_Range_start := 15%usize;
        core_ops_range_Range_end_ := 31%usize
      |};
  let (s2, index_mut_back1) := p1 in
  let s3 := array_to_slice nonce in
  s4 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s2 s3;
  let pre2 := index_mut_back1 s4 in
  p2 <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre2
      {|
        core_ops_range_Range_start := 31%usize;
        core_ops_range_Range_end_ := 35%usize
      |};
  let (s5, index_mut_back2) := p2 in
  let a := core_num_U32_to_le_bytes author_id in
  let s6 := array_to_slice a in
  s7 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s5 s6;
  let pre3 := index_mut_back2 s7 in
  p3 <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre3
      {|
        core_ops_range_Range_start := 35%usize;
        core_ops_range_Range_end_ := 39%usize
      |};
  let (s8, index_mut_back3) := p3 in
  let a1 := core_num_U32_to_le_bytes version in
  let s9 := array_to_slice a1 in
  s10 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s8 s9;
  let pre4 := index_mut_back3 s10 in
  p4 <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre4
      {|
        core_ops_range_Range_start := 39%usize;
        core_ops_range_Range_end_ := 43%usize
      |};
  let (s11, index_mut_back4) := p4 in
  let a2 := core_num_U32_to_le_bytes blob_len in
  let s12 := array_to_slice a2 in
  s13 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s11 s12;
  let pre5 := index_mut_back4 s13 in
  p5 <-
    core_array_Array_index_mut (core_ops_index_IndexMutSliceInst
      (core_slice_index_SliceIndexRangeUsizeSliceInst u8)) pre5
      {|
        core_ops_range_Range_start := 43%usize;
        core_ops_range_Range_end_ := 91%usize
      |};
  let (s14, index_mut_back5) := p5 in
  let s15 := array_to_slice header in
  s16 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s14 s15;
  let pre6 := index_mut_back5 s16 in
  pkgHmacInst.(PkgHmac_t_hmac_pkg) h key pre6
.

(** [umbra_update_core::ct_eq32]: loop body 0:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 162:4-165:5 *)
Definition ct_eq32_loop_body
  (a : array u8 32%usize) (b : slice u8) (d : u8) (i : usize) :
  result (control_flow (u8 * usize) u8)
  :=
  if i s< 32%usize
  then (
    i1 <- array_index_usize a i;
    i2 <- slice_index_usize b i;
    let i3 := u8_xor i1 i2 in
    let d1 := u8_or d i3 in
    i4 <- usize_add i 1%usize;
    Ok (Cont (d1, i4)))
  else Ok (Done d)
.

(** [umbra_update_core::ct_eq32]: loop 0:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 162:4-165:5 *)
Definition ct_eq32_loop
  (a : array u8 32%usize) (b : slice u8) (d : u8) (i : usize) : result u8 :=
  loop
    (fun '(d1, i1) => ct_eq32_loop_body a b d1 i1)
    (d, i)
.

(** [umbra_update_core::ct_eq32]:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 156:0-167:1 *)
Definition ct_eq32 (a : array u8 32%usize) (b : slice u8) : result bool :=
  let i := slice_len b in
  if i s<> 32%usize
  then Ok false
  else (d <- ct_eq32_loop a b 0%u8 0%usize; Ok (d s= 0%u8))
.

(** [umbra_update_core::ct_eq16]: loop body 0:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 150:4-153:5 *)
Definition ct_eq16_loop_body
  (a : array u8 16%usize) (b : array u8 16%usize) (d : u8) (i : usize) :
  result (control_flow (u8 * usize) u8)
  :=
  if i s< 16%usize
  then (
    i1 <- array_index_usize a i;
    i2 <- array_index_usize b i;
    let i3 := u8_xor i1 i2 in
    let d1 := u8_or d i3 in
    i4 <- usize_add i 1%usize;
    Ok (Cont (d1, i4)))
  else Ok (Done d)
.

(** [umbra_update_core::ct_eq16]: loop 0:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 150:4-153:5 *)
Definition ct_eq16_loop
  (a : array u8 16%usize) (b : array u8 16%usize) (d : u8) (i : usize) :
  result u8
  :=
  loop
    (fun '(d1, i1) => ct_eq16_loop_body a b d1 i1)
    (d, i)
.

(** [umbra_update_core::ct_eq16]:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 147:0-155:1 *)
Definition ct_eq16
  (a : array u8 16%usize) (b : array u8 16%usize) : result bool :=
  d <- ct_eq16_loop a b 0%u8 0%usize; Ok (d s= 0%u8)
.

(** [umbra_update_core::parse_and_verify]:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 90:0-134:1
    Visibility: public *)
Definition parse_and_verify
  {H : Type} (pkgHmacInst : PkgHmac_t H) (pkg : slice u8)
  (expected_nonce : array u8 16%usize) (h : H) (key : slice u8) :
  result (core_result_Result_t VerifiedUpdate_t UpdateError_t)
  :=
  let i := slice_len pkg in
  i1 <- usize_add fIXED_PREFIX mIN_BLOB;
  i2 <- usize_add i1 32%usize;
  if i s< i2
  then Ok (Core_result_Result_Err UpdateError_Malformed)
  else (
    i3 <- slice_index_usize pkg 0%usize;
    i4 <- slice_index_usize pkg 1%usize;
    i5 <- slice_index_usize pkg 2%usize;
    i6 <- slice_index_usize pkg 3%usize;
    let magic :=
      core_num_U32_from_le_bytes (mk_array4 i3 i4 i5 i6)
    in
    if magic s<> uPDATE_MAGIC
    then Ok (Core_result_Result_Err UpdateError_BadMagic)
    else (
      let nonce := array_repeat 16%usize 0%u8 in
      let (s, to_slice_mut_back) := array_to_slice_mut nonce in
      s1 <-
        core_slice_index_Slice_index
          (core_slice_index_SliceIndexRangeUsizeSliceInst u8) pkg
          {|
            core_ops_range_Range_start := 4%usize;
            core_ops_range_Range_end_ := 20%usize
          |};
      s2 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s s1;
      i7 <- slice_index_usize pkg 20%usize;
      i9 <- slice_index_usize pkg 21%usize;
      i10 <- slice_index_usize pkg 22%usize;
      i11 <- slice_index_usize pkg 23%usize;
      let author_id :=
        core_num_U32_from_le_bytes (mk_array4 i7 i9 i10 i11)
      in
      i12 <- slice_index_usize pkg 24%usize;
      i13 <- slice_index_usize pkg 25%usize;
      i14 <- slice_index_usize pkg 26%usize;
      i15 <- slice_index_usize pkg 27%usize;
      let version :=
        core_num_U32_from_le_bytes (mk_array4 i12 i13 i14 i15)
      in
      i17 <- slice_index_usize pkg 28%usize;
      i18 <- slice_index_usize pkg 29%usize;
      i19 <- slice_index_usize pkg 30%usize;
      i20 <- slice_index_usize pkg 31%usize;
      let i21 :=
        core_num_U32_from_le_bytes (mk_array4 i17 i18 i19 i20)
      in
      blob_len <- scalar_cast U32 Usize i21;
      let i22 := slice_len pkg in
      tag_off <- usize_sub i22 32%usize;
      if blob_len s< mIN_BLOB
      then Ok (Core_result_Result_Err UpdateError_Malformed)
      else (
        i23 <- usize_sub tag_off fIXED_PREFIX;
        if i23 s<> blob_len
        then Ok (Core_result_Result_Err UpdateError_Malformed)
        else (
          blob <-
            core_slice_index_Slice_index
              (core_slice_index_SliceIndexRangeUsizeSliceInst u8) pkg
              {|
                core_ops_range_Range_start := fIXED_PREFIX;
                core_ops_range_Range_end_ := tag_off
              |};
          let nonce1 := to_slice_mut_back s2 in
          b <- ct_eq16 nonce1 expected_nonce;
          if b
          then (
            let header := array_repeat 48%usize 0%u8 in
            let (s3, to_slice_mut_back1) := array_to_slice_mut header in
            s4 <-
              core_slice_index_Slice_index
                (core_slice_index_SliceIndexRangeUsizeSliceInst u8) blob
                {|
                  core_ops_range_Range_start := 0%usize;
                  core_ops_range_Range_end_ := hDR_LEN
                |};
            s5 <- core_slice_Slice_copy_from_slice core_marker_CopyU8 s3 s4;
            i24 <- scalar_cast Usize U32 blob_len;
            let header1 := to_slice_mut_back1 s5 in
            expect <-
              compute_pkg_tag pkgHmacInst nonce1 author_id version i24 header1
                h key;
            i25 <- usize_add tag_off 32%usize;
            got <-
              core_slice_index_Slice_index
                (core_slice_index_SliceIndexRangeUsizeSliceInst u8) pkg
                {|
                  core_ops_range_Range_start := tag_off;
                  core_ops_range_Range_end_ := i25
                |};
            b1 <- ct_eq32 expect got;
            if b1
            then
              Ok (Core_result_Result_Ok
                {|
                  verifiedUpdate_author_id := author_id;
                  verifiedUpdate_version := version;
                  verifiedUpdate_blob := blob
                |})
            else Ok (Core_result_Result_Err UpdateError_TagInvalid))
          else Ok (Core_result_Result_Err UpdateError_NonceMismatch)))))
.

(** [umbra_update_core::select_active_slot]:
    Source: 'crates/umbra-update-core/src/lib.rs', lines 138:0-145:1
    Visibility: public *)
Definition select_active_slot
  (ver_a : option u32) (ver_b : option u32) : result (option usize) :=
  match ver_a with
  | None =>
    match ver_b with | None => Ok None | Some _ => Ok (Some 1%usize) end
  | Some a =>
    match ver_b with
    | None => Ok (Some 0%usize)
    | Some b => if b s> a then Ok (Some 1%usize) else Ok (Some 0%usize)
    end
  end
.

End Update_Funs.
