(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_update_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes. *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Require Import Aeneas_Laws.
Local Open Scope Primitives_scope.
Require Import Update_Types.
Include Update_Types.
Module Update_FunsExternal.

(** [core::slice::{[T]}::copy_from_slice]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 4321:4-4323:16
    Name pattern: [core::slice::{[@T]}::copy_from_slice]
    Visibility: public *)
(* Filled by ../extract.sh (the template leaves it as an Axiom): bound to the
   shared library's definition (Rust panics unless the lengths match, and on
   success dst holds src's elements), so the library's laws apply verbatim. *)
Notation core_slice_Slice_copy_from_slice := Aeneas_Laws.core_slice_Slice_copy_from_slice.


(* --- the byte<->u32 codecs (NOT axioms) --------------------------------- *)
(* `u32::to_le_bytes` is the base-256 digit decomposition and
   `u32::from_le_bytes` its recomposition: the shared library's definitions,
   bound here by name so the extracted body and the library's laws (Q18/Q19)
   talk about one constant. Added by ../extract.sh. *)
Notation core_num_U32_to_le_bytes := Aeneas_Laws.core_num_U32_to_le_bytes.
Notation core_num_U32_from_le_bytes := Aeneas_Laws.core_num_U32_from_le_bytes.

(* --- TOTAL array-literal constructors (NOT axioms) ---------------------- *)
(* Replacements for the Aeneas Coq backend's `mk_array`, which is an
   inconsistent `Axiom` (see ../../AENEAS_COQ_MKARRAY_BUG.md) and which the
   library's Primitives.v therefore no longer declares. `extract.sh` rewrites
   every `mk_array N%usize [ … ]` literal in generated Update_Funs.v into an
   application of one of these. Each carries its own length proof. The 4-byte
   one is the library's (Q20 is about it); the 15-byte one is crate-specific. *)
Notation mk_array4 := Aeneas_Laws.mk_array4.

Definition mk_array15
  (b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 : u8) : array u8 15%usize :=
  exist _ [b0; b1; b2; b3; b4; b5; b6; b7; b8; b9; b10; b11; b12; b13; b14]
        eq_refl.
End Update_FunsExternal.
