(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_update_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes. *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Update_Types.
Include Update_Types.
Module Update_FunsExternal_Template.

(** [core::slice::{[T]}::copy_from_slice]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 4321:4-4323:16
    Name pattern: [core::slice::{[@T]}::copy_from_slice]
    Visibility: public *)
Axiom core_slice_Slice_copy_from_slice :
  forall{T : Type} (markerCopyInst : core_marker_Copy T),
        slice T -> slice T -> result (slice T)
.

End Update_FunsExternal_Template.
