(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_update_core]: type definitions *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Update_Types.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 557:0-557:21
    Name pattern: [core::result::Result]
    Visibility: public *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [umbra_update_core::UpdateError]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 44:0-49:1
    Visibility: public *)
Inductive UpdateError_t :=
| UpdateError_Malformed : UpdateError_t
| UpdateError_BadMagic : UpdateError_t
| UpdateError_NonceMismatch : UpdateError_t
| UpdateError_TagInvalid : UpdateError_t
.

(** [umbra_update_core::VerifiedUpdate]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 53:0-57:1
    Visibility: public *)
Record VerifiedUpdate_t :=
mkVerifiedUpdate_t {
  verifiedUpdate_author_id : u32;
  verifiedUpdate_version : u32;
  verifiedUpdate_blob : slice u8;
}
.

(** Trait declaration: [umbra_update_core::PkgHmac]
    Source: 'crates/umbra-update-core/src/lib.rs', lines 61:0-63:1
    Visibility: public *)
Record PkgHmac_t (Self : Type) := mkPkgHmac_t {
  PkgHmac_t_hmac_pkg : Self -> slice u8 -> array u8 91%usize -> result (array
    u8 32%usize);
}.

Arguments mkPkgHmac_t { _ }.
Arguments PkgHmac_t_hmac_pkg { _ } _.

End Update_Types.
