(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [umbra_update_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes. *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Require Import Update_Types.
Include Update_Types.
Module Update_FunsExternal.

(** [core::slice::{[T]}::copy_from_slice]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 4321:4-4323:16
    Name pattern: [core::slice::{[@T]}::copy_from_slice]
    Visibility: public *)
Axiom core_slice_Slice_copy_from_slice :
  forall{T : Type} (markerCopyInst : core_marker_Copy T),
        slice T -> slice T -> result (slice T)
.

Axiom core_num_U32_from_le_bytes : array u8 4%usize -> u32.
Axiom core_num_U32_to_le_bytes : u32 -> array u8 4%usize.


(* --- TOTAL array-literal constructors (NOT axioms) ---------------------- *)
(* Replacements for the Aeneas Coq backend's `Primitives.mk_array`, which is an
   inconsistent `Axiom` (see ../../AENEAS_COQ_MKARRAY_BUG.md). `extract.sh`
   rewrites every `mk_array N%usize [ … ]` literal in generated Update_Funs.v into an
   application of one of these, so no proof over the extracted body inherits the
   unsound axiom. Each carries its own length proof, so each is total and adds
   nothing to the trusted base. *)
Definition mk_array4 (b0 b1 b2 b3 : u8) : array u8 4%usize :=
  exist _ [b0; b1; b2; b3] eq_refl.

Definition mk_array15
  (b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 : u8) : array u8 15%usize :=
  exist _ [b0; b1; b2; b3; b4; b5; b6; b7; b8; b9; b10; b11; b12; b13; b14]
        eq_refl.
End Update_FunsExternal.
