/* Auto-generated by tools/image_to_c_array.py.
 * Source: coco_test.jpg
 * 224x224 RGB888 = 150528 bytes. */
#ifndef TEST_IMAGE_H
#define TEST_IMAGE_H

#include <stdint.h>

#define TEST_IMAGE_LEN (150528u)

extern const uint8_t test_image_rgb888[TEST_IMAGE_LEN];

#endif /* TEST_IMAGE_H */
