[target.thumbv8m.main-none-eabi]
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-T../../../../../host/bare_metal_arm/linker/memory.ld",
  "-C", "link-arg=-T../../../../../linker/umbra.ld",
  "-C", "link-arg=-T../linker/platform.ld"
]
[build]
target = "thumbv8m.main-none-eabi"
