/*
 * STM32N657 object-detection host.
 *
 * FreeRTOS task feeds a 224×224×3 RGB888 test image (`test_image_rgb888`,
 * generated by tools/image_to_c_array.py from a COCO val2017 photo) into
 * the model enclave at flash 0x70090000, re-enters it across SysTick
 * preemptions until the enclave terminates, then decodes the NPU's
 * Tiny YOLO v2 INT8 output via the host-side post-processor and prints
 * each detected person bounding box over UART. */

#include "FreeRTOS.h"
#include "task.h"
#include <stdint.h>
#include <stddef.h>
#include "test_image.h"
#include "postprocess.h"

/* --- NSC veneer externs -------------------------------------------------- */
extern unsigned int umbra_enclave_create(unsigned int base_addr);
extern unsigned int umbra_enclave_enter(unsigned int enclave_id);
extern unsigned int umbra_enclave_status(unsigned int enclave_id);
extern void umbra_debug_print(const char *s);

/* --- Enclave header placeholder ----------------------------------------- *
 * The linker places this 48-byte struct at the start of .app.enclave_header
 * (host.ld puts that section at VMA 0x24010000 → flash 0x70090000 after
 * flash_n657.sh writes the host bin to XSPI2 at 0x70080000). The magic +
 * placeholder fields below are overwritten by tools/protect_enclave.py at
 * build time with the real efbc_size, ess_blocks, code_size, and a 32-byte
 * HMAC over the chained-measurement of all enclave blocks. Mirrors the
 * freertos_n657 pattern verbatim. */
__attribute__((section(".app.enclave_header")))
const uint8_t enclave_header[48] = {
    0x55, 0x42, 0x4D, 0x52, /* Magic: "UMBR" (LE: 0x524D4255) */
    0x01,                    /* Trust_level (Trusted) */
    0x00,                    /* reserved */
    0x02, 0x00,              /* efbc_size — patched by protect_enclave.py */
    0x00, 0x00,              /* ess_blocks */
    0x40, 0x02, 0x00, 0x00,  /* code_size — patched */
    0x00, 0x00,              /* reserved */
    /* HMAC (32 bytes) — patched */
    0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
    0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
};

/* --- Minimal hex formatter (no printf) ----------------------------------- */
static char *u32_to_hex(uint32_t v, char *buf) {
    const char hex[] = "0123456789ABCDEF";
    buf[0] = '0'; buf[1] = 'x';
    for (int i = 0; i < 8; i++)
        buf[2 + i] = hex[(v >> ((7 - i) * 4)) & 0xF];
    buf[10] = '\0';
    return buf;
}

/* --- Inference task ------------------------------------------------------ */
static void vInferenceTask(void *pvParameters) {
    (void)pvParameters;
    char buf[11];

    umbra_debug_print("[obj-det] starting\r\n");

    /* Enclave header lives at HOST_FLASH_BASE + 0x10000 (= 0x70090000),
     * matching freertos_n657's flash layout: FSBL at 0x70000000, host bin
     * at 0x70080000, enclave header at 0x70090000. */
    unsigned int eid = umbra_enclave_create(0x70090000u);

    if (eid >= 0xFFFF0000u) {
        umbra_debug_print("[obj-det] enclave_create FAILED ");
        umbra_debug_print(u32_to_hex(eid, buf));
        umbra_debug_print("\r\n");
        for (;;) vTaskDelay(pdMS_TO_TICKS(1000));
    }

    umbra_debug_print("[obj-det] eid=");
    umbra_debug_print(u32_to_hex(eid, buf));
    umbra_debug_print("\r\n");

    /* Populate INPUT_SHARED. Header magic + length, then the 150528-byte
     * RGB888 image bytes generated from a COCO val2017 sample by
     * tools/image_to_c_array.py. */
    volatile uint8_t  *in_bytes  = (volatile uint8_t  *)0x24080000u;
    volatile uint32_t *in_hdr    = (volatile uint32_t *)0x24080000u;
    volatile uint8_t  *out_bytes = (volatile uint8_t  *)0x240C0000u;
    volatile uint32_t *out_hdr   = (volatile uint32_t *)0x240C0000u;
    in_hdr[0] = 0x554D4231u;     /* INFER_MAGIC */
    in_hdr[1] = TEST_IMAGE_LEN;
    in_hdr[2] = 0u;
    in_hdr[3] = 0u;
    for (uint32_t i = 0; i < TEST_IMAGE_LEN; i++) {
        in_bytes[16 + i] = test_image_rgb888[i];
    }
    out_hdr[0] = 0u;

    /* Re-enter the enclave across SysTick preemptions until it
     * Terminates (state 4) or Faults (state 5). */
    unsigned int enter_ret = 0;
    unsigned int reentries = 0;
    const unsigned int MAX_REENTRIES = 1000000;
    while (reentries < MAX_REENTRIES) {
        enter_ret = umbra_enclave_enter(eid);
        unsigned int state = (enter_ret >> 8) & 0xFFu;
        if (state == 0x04u) break;
        if (state == 0x05u) break;
        reentries++;
    }

    umbra_debug_print("[obj-det] enter_ret=");
    umbra_debug_print(u32_to_hex(enter_ret, buf));
    umbra_debug_print(" status=");
    umbra_debug_print(u32_to_hex(out_hdr[0], buf));
    umbra_debug_print("\r\n");

    /* Decode the 1470-byte NPU output (Tiny YOLO v2 INT8 logits) into
     * person detections. Output bytes live in OUTPUT_SHARED at offset 64
     * (= out_hdr[16]), written by the enclave's run_inference. */
    detection_t dets[YOLO_MAX_DETS];
    float max_conf = 0.0f;
    uint32_t n = yolo_decode((const uint8_t *)&out_bytes[64], dets, &max_conf);
    /* max_conf ‰ = max confidence × 1000, expressed as uint16 hex to fit
     * our u32_to_hex helper. Zero ⇒ NPU produced uniform low output. */
    uint32_t max_conf_per_mille = (uint32_t)(max_conf * 1000.0f);
    umbra_debug_print("[obj-det] detections=");
    umbra_debug_print(u32_to_hex(n, buf));
    umbra_debug_print(" max_conf‰=");
    umbra_debug_print(u32_to_hex(max_conf_per_mille, buf));
    umbra_debug_print("\r\n");

    for (uint32_t i = 0; i < n; i++) {
        /* Scale normalized box to pixel coords (224×224 input space) for
         * a more legible UART line. Pack as four uint16_t (cx, cy, w, h)
         * plus a uint16_t confidence ×1000. */
        uint16_t cx = (uint16_t)(dets[i].x * 224.0f);
        uint16_t cy = (uint16_t)(dets[i].y * 224.0f);
        uint16_t bw = (uint16_t)(dets[i].w * 224.0f);
        uint16_t bh = (uint16_t)(dets[i].h * 224.0f);
        uint16_t conf_per_mille = (uint16_t)(dets[i].confidence * 1000.0f);
        umbra_debug_print("[obj-det] person cx=");
        umbra_debug_print(u32_to_hex((uint32_t)cx, buf));
        umbra_debug_print(" cy=");
        umbra_debug_print(u32_to_hex((uint32_t)cy, buf));
        umbra_debug_print(" w=");
        umbra_debug_print(u32_to_hex((uint32_t)bw, buf));
        umbra_debug_print(" h=");
        umbra_debug_print(u32_to_hex((uint32_t)bh, buf));
        umbra_debug_print(" conf‰=");
        umbra_debug_print(u32_to_hex((uint32_t)conf_per_mille, buf));
        umbra_debug_print("\r\n");
    }

    for (;;) vTaskDelay(pdMS_TO_TICKS(1000));
}

/* --- FreeRTOS hooks ------------------------------------------------------ */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    (void)xTask;
    (void)pcTaskName;
    umbra_debug_print("[obj-det] STACK OVERFLOW!\r\n");
    while (1) {}
}

/* --- SCB.SHCSR: enable MemManage / BusFault / UsageFault in NS ----------- */
#define SCB_SHCSR (*(volatile uint32_t *)0xE000ED24u)

int main(void) {
    /* Enable NS fault handlers before anything else. */
    SCB_SHCSR |= (1u << 16) | (1u << 17) | (1u << 18);

    umbra_debug_print("[obj-det] Starting FreeRTOS scheduler\r\n");

    xTaskCreate(
        vInferenceTask, /* task function  */
        "InfTask",      /* debug name     */
        2048,           /* stack (words)  */
        NULL,           /* parameters     */
        1,              /* priority       */
        NULL            /* handle         */
    );

    vTaskStartScheduler();

    umbra_debug_print("[obj-det] ERROR: scheduler returned\r\n");
    while (1) {}
    return 0;
}
