#!/usr/bin/env python3
"""
Extract NPU bytecode array from network_ecblobs.h into a raw little-endian
binary plus a manifest JSON describing its size and entry offset.

Used by Phase G.2.b to flash the bytecode separately from the host binary
so the FSBL can boot-measure it via chained HMAC.

Usage:
    extract_bytecode.py <model_dir> <out_dir>

Inputs:
    <model_dir>/network_ecblobs.h    Generated by ST Edge AI tools.

Outputs:
    <out_dir>/model_bytecode.bin     Raw little-endian uint64 stream.
    <out_dir>/model_manifest.json    {"size": N, "entry_offset": 0}
"""
import json
import re
import struct
import sys
from pathlib import Path

HEX_PAT = re.compile(r"0x([0-9a-fA-F]+)UL")
# Match `_ec_blob_<anything>[<optional size>]`. The regenerated model
# uses `_ec_blob_1[]` (no declared size, no `_network_` infix) while
# the upstream blob used `_ec_blob_network_1[3800]`. Accept both.
ARRAY_DECL_PAT = re.compile(r"_ec_blob_\w+\s*\[\s*(\d*)\s*\]")


def main(in_dir: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    src = in_dir / "network_ecblobs.h"
    if not src.exists():
        sys.exit(f"missing: {src}")

    text = src.read_text()
    # Find the declared array size if any (e.g. `_ec_blob_network_1[3800]`).
    decl_match = ARRAY_DECL_PAT.search(text)
    if not decl_match:
        sys.exit("array declaration `_ec_blob_*[]` not found in network_ecblobs.h")
    size_str = decl_match.group(1)
    declared_size = int(size_str) if size_str else None

    # Find the array body between `{` and the matching `};`.
    open_idx = text.find("{", decl_match.start())
    if open_idx < 0:
        sys.exit("`{` not found after array name")
    close_idx = text.find("};", open_idx)
    if close_idx < 0:
        sys.exit("`};` not found")

    body = text[open_idx + 1:close_idx]
    values = [int(m.group(1), 16) for m in HEX_PAT.finditer(body)]
    if len(values) == 0:
        sys.exit("no hex values found in array body")

    # If the array declares an explicit size larger than the listed values,
    # C zero-initialises the trailing elements — pad to match.
    if declared_size is not None:
        if len(values) < declared_size:
            values.extend([0] * (declared_size - len(values)))
        elif len(values) > declared_size:
            sys.exit(f"more initialiser values ({len(values)}) than declared size ({declared_size})")

    out_bin = b"".join(struct.pack("<Q", v) for v in values)
    (out_dir / "model_bytecode.bin").write_bytes(out_bin)

    manifest = {"size": len(out_bin), "entry_offset": 0, "n_words": len(values)}
    (out_dir / "model_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote {len(out_bin)} bytes ({len(values)} u64 words) to {out_dir / 'model_bytecode.bin'}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <model_dir> <out_dir>")
    main(Path(sys.argv[1]), Path(sys.argv[2]))
