import os


def main():
    # 1. The key.
    #
    # `UMBRA_KEEP_MASTER_KEY=1` reuses the key already on disk instead of
    # rotating, so a flash-and-measure session keeps one key from end to end.
    # `cargo xtask flash` already honours the same variable at the other end: it
    # normally reverts all four key files with `git checkout HEAD --` once the
    # session is over (deliberately — a rotated key must never be committed),
    # and skips that revert when the variable is set. Honouring it here too
    # means the key does not move at all during such a session, which is what
    # tools/eval_attest.sh and tools/make_update_blob.sh assume when they tell
    # you to export it.
    #
    # Rewriting every copy from the stored key also REPAIRS a diverged tree.
    # That matters because the revert restores whatever is committed, and the
    # committed copies had drifted to four different keys — a freshly flashed
    # N657 then answers every attestation quote with `tag: FAIL` while looking
    # healthy (2026-08-10). `tools/test_attestation_guard.py` now fails loudly
    # on that state instead of leaving it to be rediscovered on a board.
    keep = os.environ.get("UMBRA_KEEP_MASTER_KEY") == "1"

    # 2. Paths
    # Assumes run from root of repo or via Makefile
    # We will make paths relative to this script location if possible, or just hardcode for this project structure
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)
    
    bin_path = os.path.join(root_dir, "tools", "master_key.bin")
    # Every Rust copy of the master key the FSBL might read at boot. Keeping
    # this list and `bin_path` in sync is what lets protect_enclave.py
    # (which reads bin_path) and the FSBL (which compiles in the Rust
    # constant) agree on the same key. The L552 path was here historically;
    # the N657 file used to be a stale L5 copy and broke chained-measurement
    # validation until added here.
    rust_paths = [
        os.path.join(root_dir, "src", "hardware", "platform", "stm32l552", "boot", "src", "master_key.rs"),
        os.path.join(root_dir, "src", "hardware", "platform", "stm32n657", "boot", "src", "master_key.rs"),
        os.path.join(root_dir, "src", "hardware", "platform", "riscv32", "boot", "src", "master_key.rs"),
    ]

    # 3. Pick the key, then write the binary copy.
    if keep and os.path.exists(bin_path):
        with open(bin_path, "rb") as f:
            key = f.read()
        if len(key) != 32:
            raise SystemExit(
                f"[KeyGen] {bin_path} is {len(key)} bytes, expected 32 — refusing to "
                "reuse a truncated key. Unset UMBRA_KEEP_MASTER_KEY to rotate."
            )
        print(f"[KeyGen] Reusing {bin_path} (UMBRA_KEEP_MASTER_KEY=1)")
    else:
        key = os.urandom(32)
        with open(bin_path, "wb") as f:
            f.write(key)
        print(f"[KeyGen] Generated {bin_path}")

    # 4. Write Rust copies (one per platform).
    rust_content =  "// Auto-generated by tools/gen_key.py\n"
    rust_content += "// Do not edit manually\n\n"
    rust_content += "pub const MASTER_KEY: [u8; 32] = [\n"

    for i, byte in enumerate(key):
        rust_content += f"    0x{byte:02X}, "
        if (i + 1) % 8 == 0:
            rust_content += "\n"

    rust_content += "];\n"

    for rust_path in rust_paths:
        with open(rust_path, "w") as f:
            f.write(rust_content)
        print(f"[KeyGen] Generated {rust_path}")

if __name__ == "__main__":
    main()
