import os
import sys

def main():
    # 1. Generate 32 bytes
    key = os.urandom(32)
    
    # 2. Paths
    # Assumes run from root of repo or via Makefile
    # We will make paths relative to this script location if possible, or just hardcode for this project structure
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)
    
    bin_path = os.path.join(root_dir, "tools", "master_key.bin")
    rust_path = os.path.join(root_dir, "src", "hardware", "platform", "stm32l552", "boot", "src", "master_key.rs")
    
    # 3. Write Bin
    with open(bin_path, "wb") as f:
        f.write(key)
        
    print(f"[KeyGen] Generated {bin_path}")
    
    # 4. Write Rust
    rust_content =  "// Auto-generated by tools/gen_key.py\n"
    rust_content += "// Do not edit manually\n\n"
    rust_content += "pub const MASTER_KEY: [u8; 32] = [\n"
    
    for i, byte in enumerate(key):
        rust_content += f"    0x{byte:02X}, "
        if (i + 1) % 8 == 0:
            rust_content += "\n"
            
    rust_content += "];\n"
    
    with open(rust_path, "w") as f:
        f.write(rust_content)
        
    print(f"[KeyGen] Generated {rust_path}")

if __name__ == "__main__":
    main()
