#!/usr/bin/env python3
"""Convert any image to a 224x224 RGB888 C array header for the Umbra
N657 obj-det demo.

Usage:
    image_to_c_array.py <input_image> <output_header>

Examples:
    image_to_c_array.py person.jpg host/object_detection_n657/inc/test_image.h

The output header defines:
    extern const uint8_t test_image_rgb888[224 * 224 * 3];
    extern const uint32_t test_image_len;
plus a .c file emitted next to it with the actual bytes.

Requires Pillow:
    pip install Pillow
"""
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("error: Pillow not installed. Run: pip install Pillow")


TARGET_SIZE = 224
CHANNELS = 3
IMAGE_LEN = TARGET_SIZE * TARGET_SIZE * CHANNELS


def main(in_path: Path, out_header: Path) -> None:
    if not in_path.exists():
        sys.exit(f"error: input image not found: {in_path}")

    img = Image.open(in_path).convert("RGB")
    # Letterbox to 224x224 keeping aspect ratio (so feature stays centered).
    img.thumbnail((TARGET_SIZE, TARGET_SIZE), Image.LANCZOS)
    canvas = Image.new("RGB", (TARGET_SIZE, TARGET_SIZE), (0, 0, 0))
    pad_x = (TARGET_SIZE - img.width) // 2
    pad_y = (TARGET_SIZE - img.height) // 2
    canvas.paste(img, (pad_x, pad_y))

    raw = canvas.tobytes()  # RGB888 interleaved
    if len(raw) != IMAGE_LEN:
        sys.exit(f"unexpected raw length {len(raw)} (expected {IMAGE_LEN})")

    out_header = out_header.resolve()
    # Put the generated .c in the sibling src/ directory (where the build
    # picks up sources), not next to the header.
    src_dir = out_header.parent.parent / "src"
    out_source = src_dir / out_header.with_suffix(".c").name
    out_header.parent.mkdir(parents=True, exist_ok=True)
    src_dir.mkdir(parents=True, exist_ok=True)

    # Header: declarations only.
    out_header.write_text(
        "/* Auto-generated by tools/image_to_c_array.py.\n"
        f" * Source: {in_path.name}\n"
        f" * 224x224 RGB888 = {IMAGE_LEN} bytes. */\n"
        "#ifndef TEST_IMAGE_H\n"
        "#define TEST_IMAGE_H\n\n"
        "#include <stdint.h>\n\n"
        f"#define TEST_IMAGE_LEN ({IMAGE_LEN}u)\n\n"
        f"extern const uint8_t test_image_rgb888[TEST_IMAGE_LEN];\n\n"
        "#endif /* TEST_IMAGE_H */\n"
    )

    # Source: bytes as comma-separated hex, 16 per line for readability.
    lines = []
    lines.append(f"/* Auto-generated by tools/image_to_c_array.py from {in_path.name}. */\n")
    lines.append('#include "test_image.h"\n\n')
    lines.append(
        "const uint8_t test_image_rgb888[TEST_IMAGE_LEN]\n"
        '    __attribute__((section(".test_image_data"))) = {\n'
    )
    for i in range(0, len(raw), 16):
        chunk = raw[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    lines.append("};\n")
    out_source.write_text("".join(lines))

    print(f"[image_to_c_array] {in_path} -> {out_header}")
    print(f"[image_to_c_array]              {out_source}")
    print(f"[image_to_c_array] {IMAGE_LEN} bytes (224x224x3 RGB888)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <input_image> <output_header>")
    main(Path(sys.argv[1]), Path(sys.argv[2]))
