#!/usr/bin/env python3
"""
Compute boot-time HMACs over model_bytecode.bin and network_data.xSPI2.bin
and emit boot_measurements.rs with the expected HMACs as Rust constants.

The FSBL recomputes these chains at boot via
`secure_kernel::measure_boot_blobs` and halts on mismatch. Algorithm: state
seeded with the master key, fold 256-byte chunks via HMAC-SHA256, zero-pad
the final chunk. Must stay byte-for-byte aligned with the FSBL.

Usage:
    measure_blobs.py <master_key.bin> <bytecode.bin> <weights.bin> <out.rs>
"""
import hmac
import hashlib
import sys
from pathlib import Path

CHUNK = 256


def chained_hmac(key: bytes, data: bytes) -> bytes:
    state = key
    for off in range(0, len(data), CHUNK):
        chunk = data[off:off + CHUNK]
        if len(chunk) < CHUNK:
            chunk = chunk + b"\x00" * (CHUNK - len(chunk))
        state = hmac.new(state, chunk, hashlib.sha256).digest()
    return state


def main(key_path: Path, bc_path: Path, wt_path: Path, out_path: Path) -> None:
    key = key_path.read_bytes()
    if len(key) != 32:
        sys.exit(f"master_key.bin must be 32 bytes, got {len(key)}")
    bc = bc_path.read_bytes()
    wt = wt_path.read_bytes()

    bc_hmac = chained_hmac(key, bc)
    wt_hmac = chained_hmac(key, wt)

    lines = [
        "// Auto-generated by tools/measure_blobs.py — DO NOT EDIT.",
        "// Boot-time chained-HMAC constants. The FSBL's",
        "// `measure_boot_blobs()` recomputes these chains over the flashed",
        "// regions and halts boot on mismatch.",
        "",
        "pub const MODEL_BYTECODE_ADDR: u32 = 0x7020_0000;",
        f"pub const MODEL_BYTECODE_LEN: u32 = {len(bc)};",
        f"pub const MODEL_BYTECODE_HMAC: [u8; 32] = {list(bc_hmac)};",
        "",
        "pub const MODEL_WEIGHTS_ADDR: u32 = 0x7038_0000;",
        f"pub const MODEL_WEIGHTS_LEN: u32 = {len(wt)};",
        f"pub const MODEL_WEIGHTS_HMAC: [u8; 32] = {list(wt_hmac)};",
        "",
    ]
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}: bytecode={len(bc)}B, weights={len(wt)}B")


if __name__ == "__main__":
    if len(sys.argv) != 5:
        sys.exit(f"usage: {sys.argv[0]} <key.bin> <bc.bin> <wt.bin> <out.rs>")
    main(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]), Path(sys.argv[4]))
