//! umbra-ess-core — the Enclave Swapping Set (ESS) cache logic, carved out of
//! `src/kernel/src/common/ess.rs` for issue #58 so it can be machine-checked.
//!
//! This is the REAL logic (copied verbatim from the kernel), not a re-model.
//! It is `#![no_std]` with **zero `unsafe`**: the hardware seams (DMA fetch,
//! HMAC/AES, MPCBB/RISAF slot flips, trap-fill) live in the per-platform boot
//! crates and are NOT here — they are the opaque boundary of the model.
//!
//! Phase 3b will switch `kernel::common::ess` to re-export from this crate so
//! the firmware and the extracted Coq model share a single source of truth.
#![no_std]

use umbra_error::{UmbraError, UmbraResult};

// Reject building with more than one platform feature enabled — the cfg-gated
// constants below would conflict.
#[cfg(any(
    all(feature = "platform-l552", feature = "platform-n657"),
    all(feature = "platform-l552", feature = "platform-riscv32"),
    all(feature = "platform-n657", feature = "platform-riscv32"),
))]
compile_error!(
    "Enable exactly ONE of features platform-l552 / platform-n657 / platform-riscv32"
);

// ── L552 platform ESS layout ─────────────────────────────────────────
#[cfg(feature = "platform-l552")]
pub const ESS_BASE: u32 = 0x30032000;
#[cfg(feature = "platform-l552")]
pub const ESS_SIZE: u32 = 0x10000;
#[cfg(feature = "platform-l552")]
pub const EFBC_BASE: u32 = 0x20020000;
#[cfg(feature = "platform-l552")]
pub const ENCLAVE_PSP_BASE: u32 = 0x30034000;
#[cfg(feature = "platform-l552")]
pub const ENCLAVE_PSP_TOP: u32 = 0x30038000;

// ── N657 platform ESS layout ─────────────────────────────────────────
#[cfg(feature = "platform-n657")]
pub const ESS_BASE: u32 = 0x340E0000;
#[cfg(feature = "platform-n657")]
pub const ESS_SIZE: u32 = 0x10000;
#[cfg(feature = "platform-n657")]
pub const EFBC_BASE: u32 = 0x340E0000;
#[cfg(feature = "platform-n657")]
pub const ENCLAVE_PSP_BASE: u32 = 0x340F0000;
#[cfg(feature = "platform-n657")]
pub const ENCLAVE_PSP_TOP: u32 = 0x340F4000;

// ── RISC-V RV32 (QEMU virt) platform ESS layout ──────────────────────
#[cfg(feature = "platform-riscv32")]
pub const ESS_BASE: u32 = 0x80200000;
#[cfg(feature = "platform-riscv32")]
pub const ESS_SIZE: u32 = 0x10000;
#[cfg(feature = "platform-riscv32")]
pub const EFBC_BASE: u32 = 0x80200000;
#[cfg(feature = "platform-riscv32")]
pub const ENCLAVE_PSP_BASE: u32 = 0x80210000;
#[cfg(feature = "platform-riscv32")]
pub const ENCLAVE_PSP_TOP: u32 = 0x80218000;

// ── Host / Charon-extraction defaults (no platform feature) ──────────
// The logic is identical on every target; only these addresses differ. Host
// values are arbitrary but satisfy the PSP-region static assert below. They are
// never used by firmware (which always selects a platform feature) — they exist
// so the crate builds for the host so Charon/Aeneas can extract the model.
#[cfg(not(any(
    feature = "platform-l552",
    feature = "platform-n657",
    feature = "platform-riscv32"
)))]
pub const ESS_BASE: u32 = 0x0001_0000;
#[cfg(not(any(
    feature = "platform-l552",
    feature = "platform-n657",
    feature = "platform-riscv32"
)))]
pub const ESS_SIZE: u32 = 0x10000;
#[cfg(not(any(
    feature = "platform-l552",
    feature = "platform-n657",
    feature = "platform-riscv32"
)))]
pub const EFBC_BASE: u32 = 0x0002_0000;
#[cfg(not(any(
    feature = "platform-l552",
    feature = "platform-n657",
    feature = "platform-riscv32"
)))]
pub const ENCLAVE_PSP_BASE: u32 = 0x0003_0000;
#[cfg(not(any(
    feature = "platform-l552",
    feature = "platform-n657",
    feature = "platform-riscv32"
)))]
pub const ENCLAVE_PSP_TOP: u32 = 0x0003_4000;

// Build-time knobs: SLOT_SIZE, CACHE_LIMIT_PER_ENCLAVE, MAX_ENCLAVES_CTX,
// ENCLAVE_PSP_STACK_SIZE, MAX_KEYS. Generated by build.rs from the same env
// knobs the kernel uses (workspace .cargo/config.toml [env]).
include!(concat!(env!("OUT_DIR"), "/sizes_generated.rs"));

// MAX_EFBS covers paper-app `statemate` (41 blocks). The `loaded_mask` bitmap
// in api_impl.rs is u64 — its width MUST match this ceiling.
pub const MAX_EFBS: usize = 64;
pub const MAX_REACHABLE: usize = 4;

// Static guard: MAX_ENCLAVES_CTX × ENCLAVE_PSP_STACK_SIZE must fit in the PSP
// region. Catches knob mis-configuration at build time.
const _: () = assert!(
    MAX_ENCLAVES_CTX * (ENCLAVE_PSP_STACK_SIZE as usize)
        <= (ENCLAVE_PSP_TOP - ENCLAVE_PSP_BASE) as usize,
    "UMBRA_MAX_ENCLAVES_CTX x UMBRA_ENCLAVE_PSP_STACK_BYTES exceeds the PSP region"
);

/// Per-enclave descriptor. Carved out of `kernel::common::enclave` (the POD
/// half — the `unsafe` context-switch code stays in the kernel).
#[derive(Copy, Clone)]
pub struct EnclaveDescriptor {
    pub id: u32,
    pub flash_base: u32,
    pub ram_base: u32,
    pub code_size: u32,
    pub entry_point: u32,
    pub is_loaded: bool,
}

impl EnclaveDescriptor {
    pub fn new() -> Self {
        Self {
            id: 0,
            flash_base: 0,
            ram_base: 0,
            code_size: 0,
            entry_point: 0,
            is_loaded: false,
        }
    }
}

pub fn enclave_psp_top(enclave_idx: usize) -> u32 {
    ENCLAVE_PSP_TOP - (enclave_idx as u32) * ENCLAVE_PSP_STACK_SIZE
}

#[derive(Clone, Copy)]
pub struct EnclaveSwapSpace {
    pub base_address: u32,
    pub size: u32,
    pub loaded_enclaves: [Option<LoadedEnclave>; MAX_ENCLAVES_CTX],
    pub bitmap: [u32; 8], // 256 slots (256 * 256B = 64KB)
}

#[derive(Clone, Copy)]
pub struct EfbDescriptor {
    pub id: u32,
    pub is_loaded: bool,
    pub counter: u8,
    pub reachable: [u8; MAX_REACHABLE],
    pub reachable_count: u8,
}

impl Default for EfbDescriptor {
    fn default() -> Self {
        Self {
            id: 0,
            is_loaded: false,
            counter: 0,
            reachable: [0; MAX_REACHABLE],
            reachable_count: 0,
        }
    }
}

#[derive(Clone, Copy)]
pub struct LoadedEnclave {
    pub descriptor: EnclaveDescriptor,
    pub start_address: u32,
    pub efbs: [EfbDescriptor; MAX_EFBS],
    pub efb_count: usize,
}

impl EnclaveSwapSpace {
    pub fn new() -> Self {
        Self {
            base_address: ESS_BASE,
            size: ESS_SIZE,
            loaded_enclaves: [None; MAX_ENCLAVES_CTX],
            bitmap: [0; 8],
        }
    }

    /// First-fit allocate a contiguous run of ESS slots for `size` bytes.
    ///
    /// Split into a pure search (`find_free_run`, `&self`) and a separate
    /// mutation (`mark_slots_used`): Aeneas cannot translate a `&mut self`
    /// mutation that lives *inside* a loop which early-returns. Keeping the
    /// search loop borrow-free and doing the bitmap write after it is
    /// behavior-preserving and translates cleanly (issue #58).
    pub fn allocate(&mut self, size: u32) -> UmbraResult<u32> {
        let slots_needed = size
            .checked_add(SLOT_SIZE - 1)
            .ok_or(UmbraError::OffsetOverflow)?
            / SLOT_SIZE;
        if slots_needed == 0 {
            return Err(UmbraError::LengthMismatch);
        }
        match self.find_free_run(slots_needed) {
            Some(found_start) => {
                self.mark_slots_used(found_start, slots_needed as usize);
                Ok(EFBC_BASE + (found_start as u32 * SLOT_SIZE))
            }
            None => Err(UmbraError::EssRegionExhausted),
        }
    }

    /// First-fit search for a contiguous run of `slots_needed` free slots.
    /// Pure (`&self`): returns the starting slot index, or `None` if no run
    /// fits. The bitmap is not modified here.
    fn find_free_run(&self, slots_needed: u32) -> Option<usize> {
        let total_slots = (ESS_SIZE / SLOT_SIZE) as usize;
        // Only two loop-carried variables (`found_count`, `i`): tracking the run
        // start as a third, conditionally-assigned variable made Aeneas's loop
        // fixed-point analysis diverge ("Could not compute a loop fixed point").
        // The run of `slots_needed` consecutive free slots ending at `i` starts
        // at `i + 1 - slots_needed`. Behavior-preserving (issue #58).
        let mut found_count: u32 = 0;
        let mut i: usize = 0;
        while i < total_slots {
            let word_idx = i / 32;
            let bit_idx = i % 32;

            if (self.bitmap[word_idx] & (1 << bit_idx)) == 0 {
                found_count += 1;
            } else {
                found_count = 0;
            }

            if found_count == slots_needed {
                return Some(i + 1 - slots_needed as usize);
            }
            i += 1;
        }
        None
    }

    /// Mark `count` bitmap slots used starting at slot index `start`.
    fn mark_slots_used(&mut self, start: usize, count: usize) {
        let mut k: usize = 0;
        while k < count {
            let idx = start + k;
            self.bitmap[idx / 32] |= 1 << (idx % 32);
            k += 1;
        }
    }

    /// Release an allocated slot run back to the free bitmap.
    pub fn release(&mut self, address: u32, size: u32) {
        if address < EFBC_BASE {
            return;
        }
        let slot_offset = (address - EFBC_BASE) / SLOT_SIZE;
        let slots = (size + SLOT_SIZE - 1) / SLOT_SIZE;
        let mut k: u32 = 0;
        while k < slots {
            let idx = (slot_offset + k) as usize;
            const BITMAP_CAPACITY: usize = 256;
            if idx < BITMAP_CAPACITY {
                self.bitmap[idx / 32] &= !(1u32 << (idx % 32));
            }
            k += 1;
        }
    }

    pub fn register_enclave(
        &mut self,
        descriptor: EnclaveDescriptor,
        address: u32,
        efbs: [EfbDescriptor; MAX_EFBS],
        efb_count: usize,
    ) -> bool {
        for slot in self.loaded_enclaves.iter_mut() {
            if slot.is_none() {
                *slot = Some(LoadedEnclave {
                    descriptor,
                    start_address: address,
                    efbs,
                    efb_count,
                });
                return true;
            }
        }
        false
    }

    // Formal Model Support: "Check Cache"
    pub fn get_block_address(&self, enclave_id: u32, block_id: u32) -> Option<u32> {
        for enc in self.loaded_enclaves.iter() {
            if let Some(e) = enc {
                if e.descriptor.id == enclave_id {
                    if (block_id as usize) < e.efb_count {
                        let efb = &e.efbs[block_id as usize];
                        if efb.is_loaded && efb.id == block_id {
                            return block_id
                                .checked_mul(SLOT_SIZE)
                                .and_then(|x| e.start_address.checked_add(x));
                        }
                    }
                }
            }
        }
        None
    }
}

impl LoadedEnclave {
    pub fn loaded_count(&self) -> usize {
        // Explicit while loop instead of `.iter().filter().count()`: Aeneas
        // cannot translate the iterator-combinator chain ("Region ids should not
        // be visited directly"). Behavior-preserving (issue #58).
        let mut count = 0;
        let mut i = 0;
        while i < self.efb_count {
            if self.efbs[i].is_loaded {
                count += 1;
            }
            i += 1;
        }
        count
    }

    pub fn find_eviction_victim(&self, exclude_idx: u32) -> Option<u32> {
        let mut best: Option<(u32, u8)> = None;

        for i in 1..self.efb_count {
            let efb = &self.efbs[i];
            if efb.is_loaded && (i as u32) != exclude_idx {
                match best {
                    None => best = Some((i as u32, efb.counter)),
                    Some((_, bc)) if efb.counter < bc => best = Some((i as u32, efb.counter)),
                    _ => {}
                }
            }
        }
        best.map(|(idx, _)| idx)
    }
}

// Sanity check on the first-fit allocator + eviction — the smallest test that
// fails if the bookkeeping breaks. Not part of the Aeneas pipeline.
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn allocate_release_roundtrip() {
        let mut ess = EnclaveSwapSpace::new();
        let a = ess.allocate(SLOT_SIZE).expect("first alloc fits");
        assert_eq!(a, EFBC_BASE);
        // A second allocation must not overlap the first.
        let b = ess.allocate(SLOT_SIZE).expect("second alloc fits");
        assert_ne!(a, b);
        // Releasing the first frees its slot for re-allocation at the same addr.
        ess.release(a, SLOT_SIZE);
        let c = ess.allocate(SLOT_SIZE).expect("re-alloc after release");
        assert_eq!(c, a);
    }

    #[test]
    fn lfu_victim_picks_lowest_counter() {
        let mut enc = LoadedEnclave {
            descriptor: EnclaveDescriptor::new(),
            start_address: EFBC_BASE,
            efbs: [EfbDescriptor::default(); MAX_EFBS],
            efb_count: 4,
        };
        for i in 0..4 {
            enc.efbs[i].is_loaded = true;
            enc.efbs[i].counter = (i as u8) + 1;
        }
        // Block 0 is excluded (entry); lowest counter among 1..4 is block 1.
        assert_eq!(enc.find_eviction_victim(0), Some(1));
    }
}
